/**
 * Stage RDKit into `packages/client/public/rdkit/`.
 *
 * Four files land there and none of them go through the bundler:
 *
 *   RDKit_minimal.wasm       6.9 MB, copied verbatim from the package
 *   RDKit_minimal.js         the emscripten glue, copied verbatim
 *   rdkit.worker.js          src/lib/rdkit/worker.ts, bundled by esbuild
 *   THIRD-PARTY-NOTICES.txt  the licences that travel with the wasm
 *
 * WHY public/ AND NOT THE BUNDLER. No bundler emits the wasm anyway — the
 * glue names it as the plain string "RDKit_minimal.wasm" inside a runtime
 * lookup, with no `new URL(...)` and no `import.meta` for a bundler to see.
 * And routing the WORKER through Turbopack is actively wrong: it resolves the
 * emitted chunk against `location.origin`, which drops any subpath the static
 * export is served under, 404s, and reports it as an error event with an
 * empty message. `public/` is copied verbatim in both `output:"standalone"`
 * and `output:"export"`, so one staging step covers both.
 *
 * WHY esbuild RATHER THAN A HAND-WRITTEN WORKER. The JSMol lifetime rules and
 * the change reporting are the part of this bridge most worth typechecking
 * and unit-testing; leaving them in an unchecked file under public/ would put
 * them beyond the reach of both.
 *
 * Chained explicitly from `dev` and `build` rather than hung off a `prebuild`
 * hook: whether pnpm runs `prebuild` has varied across versions, and this
 * repo pins a different pnpm than the one on any given machine.
 */

import { createRequire } from "node:module";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import * as esbuild from "esbuild";

const require = createRequire(import.meta.url);
const here = path.dirname(fileURLToPath(import.meta.url));
const clientRoot = path.join(here, "..");
const outDir = path.join(clientRoot, "public", "rdkit");

const rdkitRoot = path.dirname(require.resolve("@rdkit/rdkit/package.json"));
const version = JSON.parse(
  await readFile(path.join(rdkitRoot, "package.json"), "utf8"),
).version;

await mkdir(outDir, { recursive: true });

for (const name of ["RDKit_minimal.wasm", "RDKit_minimal.js"]) {
  // Read/write rather than copyFile: the package's dist/ files are hard
  // links into the pnpm store, and copyFile can propagate that on some
  // filesystems, which would make `public/` a writable view of the store.
  await writeFile(path.join(outDir, name), await readFile(path.join(rdkitRoot, "dist", name)));
}

await esbuild.build({
  entryPoints: [path.join(clientRoot, "src", "lib", "rdkit", "worker.ts")],
  outfile: path.join(outDir, "rdkit.worker.js"),
  bundle: true,
  // A CLASSIC worker: `importScripts` is not available in a module worker,
  // and Turbopack strips `{type:"module"}` anyway wherever it builds one.
  format: "iife",
  platform: "browser",
  target: "es2020",
  minify: true,
  legalComments: "none",
  logLevel: "warning",
});

const rdkitLicence = await readFile(path.join(rdkitRoot, "LICENSE"), "utf8");

await writeFile(
  path.join(outDir, "THIRD-PARTY-NOTICES.txt"),
  `Third-party notices for the files in this directory.

Generated by packages/client/scripts/copy-rdkit.mjs. Do not edit by hand.

RDKit_minimal.wasm and RDKit_minimal.js come from @rdkit/rdkit ${version}
(RDKit MinimalLib). The wasm statically links more than RDKit itself; every
component below is inside that one file.

===============================================================================
RDKit — BSD 3-Clause. Verbatim copy of the LICENSE file shipped in
@rdkit/rdkit ${version}.
===============================================================================

${rdkitLicence.trimEnd()}

===============================================================================
IUPAC International Chemical Identifier (InChI) Software, version 1.07.3
===============================================================================

RDKit_minimal.wasm is built with InChI support (RDK_BUILD_INCHI_SUPPORT), so
the InChI library is linked into it. The InChI Software is distributed by the
InChI Trust under the IUPAC/InChI-Trust Licence for the International Chemical
Identifier (InChI) Software, version 1.07, which is NOT the BSD licence above.
Source and licence: https://www.inchi-trust.org/

===============================================================================
Boost — Boost Software License, Version 1.0
===============================================================================

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

===============================================================================
coordgenlibs — BSD 3-Clause, Copyright (c) 2017, Schrodinger, Inc.
===============================================================================

RDKit_minimal.wasm is built with CoordGen support (RDK_BUILD_COORDGEN_SUPPORT),
which is what generate2DCoords uses. coordgenlibs carries the same BSD
3-Clause terms as RDKit, with Schrodinger, Inc. as the copyright holder.
Source and licence: https://github.com/schrodinger/coordgenlibs
`,
);

console.log(`rdkit: staged @rdkit/rdkit ${version} into packages/client/public/rdkit/`);
