/**
 * Text fixtures for the import tests, written out as literal file contents.
 *
 * Deliberately not generated by calling `writeMolblock` in the test: an
 * importer proven only against its own exporter is proven against a private
 * dialect. These are the bytes a real V2000 file contains, and the SDF is
 * shaped the way PubChem's download is — records separated by `$$$$`, a data
 * block after `M  END`, and a trailing delimiter.
 */

export const BENZENE_MOLBLOCK = `Benzene
  chemcore          2D

  6  6  0  0  0  0  0  0  0  0999 V2000
    0.0000   -1.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2990   -0.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2990    0.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    1.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2990    0.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2990   -0.7500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  2  0  0  0  0
  3  4  1  0  0  0  0
  4  5  2  0  0  0  0
  5  6  1  0  0  0  0
  6  1  2  0  0  0  0
M  END
`;

export const ETHANOL_MOLBLOCK = `Ethanol
  chemcore          2D

  3  2  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.5000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.2500    1.2990    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  1  0  0  0  0
M  END
`;

/** Three records, the way an SDF from a vendor catalogue arrives: each with
 *  its own title, a data block, and a `$$$$` after every one INCLUDING the
 *  last. Decision 7 makes this three documents. */
export const THREE_RECORD_SDF = `${BENZENE_MOLBLOCK}> <SOURCE>
catalogue

$$$$
${ETHANOL_MOLBLOCK}> <SOURCE>
catalogue

$$$$
Water-ish
  chemcore          2D

  2  1  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.5000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
M  END
$$$$
`;

/** The counts line declares two atoms; three atom rows follow. chem-core
 *  reports that as `surplus-block` and skips the extra row to keep the bond
 *  block aligned — which `@/lib/rdkit/translate` classifies as LOSSY, because
 *  a counts field that overflows past 999 silently drops most of a structure
 *  this exact way. */
export const SURPLUS_BLOCK_MOLBLOCK = `Surplus
  chemcore          2D

  2  1  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.5000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.2500    1.2990    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
M  END
`;

export const BENZENE_INCHI = "InChI=1S/C6H6/c1-2-4-6-5-3-1/h1-6H";
