/**
 * GENERATED by packages/client/scripts/build-structure-dictionary.mjs.
 * Do not edit by hand: change the source table in that script and run
 *
 *   pnpm --filter @starter/client build:dictionary
 *
 * Every molblock is RDKit's 2D layout of the row's SMILES, with the entry name
 * on the title line. `smiles` and `inchiKey` are provenance: chem-core never
 * parses either, and the client's fidelity test checks that each molblock
 * still means its SMILES.
 */

import type { DictionaryEntry } from "./dictionary.js";

export const DICTIONARY_ENTRIES: readonly DictionaryEntry[] = [
  {
    id: "water",
    name: "water",
    synonyms: [],
    category: "solvent",
    smiles: "O",
    inchiKey: "XLYOFNOQVPJJNP-UHFFFAOYSA-N",
    molblock: `water
     RDKit          2D

  1  0  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
M  END
`,
  },
  {
    id: "methanol",
    name: "methanol",
    synonyms: ["MeOH","methyl alcohol"],
    category: "solvent",
    smiles: "CO",
    inchiKey: "OKKJLVBELUTLKV-UHFFFAOYSA-N",
    molblock: `methanol
     RDKit          2D

  2  1  0  0  0  0  0  0  0  0999 V2000
   -0.5000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5000    0.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
M  END
`,
  },
  {
    id: "ethanol",
    name: "ethanol",
    synonyms: ["EtOH","ethyl alcohol","alcohol"],
    category: "solvent",
    smiles: "CCO",
    inchiKey: "LFQSCWFLJHTTHZ-UHFFFAOYSA-N",
    molblock: `ethanol
     RDKit          2D

  3  2  0  0  0  0  0  0  0  0999 V2000
    0.8659   -0.1674    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0003    0.3334    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8661   -0.1660    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
M  END
`,
  },
  {
    id: "isopropanol",
    name: "propan-2-ol",
    synonyms: ["isopropanol","isopropyl alcohol","IPA","2-propanol","iPrOH"],
    category: "solvent",
    smiles: "CC(C)O",
    inchiKey: "KFZMGEQAYNKOFK-UHFFFAOYSA-N",
    molblock: `propan-2-ol
     RDKit          2D

  4  3  0  0  0  0  0  0  0  0999 V2000
    0.8642   -0.5030    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000   -0.0001    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8678   -0.4969    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0036    0.9999    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  2  4  1  0
M  END
`,
  },
  {
    id: "acetone",
    name: "acetone",
    synonyms: ["propanone","propan-2-one"],
    category: "solvent",
    smiles: "CC(C)=O",
    inchiKey: "CSCPPACGZOOCGX-UHFFFAOYSA-N",
    molblock: `acetone
     RDKit          2D

  4  3  0  0  0  0  0  0  0  0999 V2000
    0.8642   -0.5030    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000   -0.0001    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8678   -0.4969    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0036    0.9999    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  2  4  2  0
M  END
`,
  },
  {
    id: "acetonitrile",
    name: "acetonitrile",
    synonyms: ["MeCN","methyl cyanide"],
    category: "solvent",
    smiles: "CC#N",
    inchiKey: "WEVYAHXRMPXWCK-UHFFFAOYSA-N",
    molblock: `acetonitrile
     RDKit          2D

  3  2  0  0  0  0  0  0  0  0999 V2000
   -0.8678   -0.4968    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8678    0.4968    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  3  0
M  END
`,
  },
  {
    id: "dmso",
    name: "dimethyl sulfoxide",
    synonyms: ["DMSO"],
    category: "solvent",
    smiles: "CS(C)=O",
    inchiKey: "IAZDPXIOMUYVGZ-UHFFFAOYSA-N",
    molblock: `dimethyl sulfoxide
     RDKit          2D

  4  3  0  0  0  0  0  0  0  0999 V2000
    0.8642   -0.5030    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000   -0.0001    0.0000 S   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8678   -0.4969    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0036    0.9999    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  2  4  2  0
M  END
`,
  },
  {
    id: "dmf",
    name: "N,N-dimethylformamide",
    synonyms: ["DMF","dimethylformamide"],
    category: "solvent",
    smiles: "CN(C)C=O",
    inchiKey: "ZMXDDKWLCZADIW-UHFFFAOYSA-N",
    molblock: `N,N-dimethylformamide
     RDKit          2D

  5  4  0  0  0  0  0  0  0  0999 V2000
    1.2128   -0.4990    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3464    0.0002    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.3456    1.0002    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.5192   -0.5004    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.3856   -0.0012    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  2  4  1  0
  4  5  2  0
M  END
`,
  },
  {
    id: "thf",
    name: "tetrahydrofuran",
    synonyms: ["THF","oxolane"],
    category: "solvent",
    smiles: "C1CCOC1",
    inchiKey: "WYURNTSHIVDZCO-UHFFFAOYSA-N",
    molblock: `tetrahydrofuran
     RDKit          2D

  5  5  0  0  0  0  0  0  0  0999 V2000
   -0.0934    0.8455    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8330    0.1725    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4214   -0.7389    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5726   -0.6291    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.7752    0.3501    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  1  1  0
M  END
`,
  },
  {
    id: "dioxane",
    name: "1,4-dioxane",
    synonyms: ["dioxane"],
    category: "solvent",
    smiles: "C1COCCO1",
    inchiKey: "RYHBNJHYFVUHQT-UHFFFAOYSA-N",
    molblock: `1,4-dioxane
     RDKit          2D

  6  6  0  0  0  0  0  0  0  0999 V2000
    0.0008    1.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8656    0.5006    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8664   -0.4994    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0008   -1.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8656   -0.5006    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8664    0.4994    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  6  1  0
  6  1  1  0
M  END
`,
  },
  {
    id: "dichloromethane",
    name: "dichloromethane",
    synonyms: ["DCM","methylene chloride"],
    category: "solvent",
    smiles: "ClCCl",
    inchiKey: "YMWUJEATGCHHMB-UHFFFAOYSA-N",
    molblock: `dichloromethane
     RDKit          2D

  3  2  0  0  0  0  0  0  0  0999 V2000
   -0.8666   -0.1635    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
    0.0012    0.3333    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8654   -0.1699    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
M  END
`,
  },
  {
    id: "chloroform",
    name: "chloroform",
    synonyms: ["trichloromethane"],
    category: "solvent",
    smiles: "ClC(Cl)Cl",
    inchiKey: "HEDRZPFGACZZDS-UHFFFAOYSA-N",
    molblock: `chloroform
     RDKit          2D

  4  3  0  0  0  0  0  0  0  0999 V2000
    0.0008    1.0000    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8656   -0.5006    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   -0.8664   -0.4994    0.0000 Cl  0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  2  4  1  0
M  END
`,
  },
  {
    id: "ethyl-acetate",
    name: "ethyl acetate",
    synonyms: ["EtOAc","ethyl ethanoate"],
    category: "solvent",
    smiles: "CCOC(C)=O",
    inchiKey: "XEKOWRVHYACXOJ-UHFFFAOYSA-N",
    molblock: `ethyl acetate
     RDKit          2D

  6  5  0  0  0  0  0  0  0  0999 V2000
   -1.8755   -0.4204    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0105    0.0814    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1435   -0.4170    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.7215    0.0848    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.5885   -0.4134    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7195    1.0848    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  1  0
  4  6  2  0
M  END
`,
  },
  {
    id: "diethyl-ether",
    name: "diethyl ether",
    synonyms: ["ether","Et2O","ethoxyethane"],
    category: "solvent",
    smiles: "CCOCC",
    inchiKey: "RTZKZFJDLAIYFH-UHFFFAOYSA-N",
    molblock: `diethyl ether
     RDKit          2D

  5  4  0  0  0  0  0  0  0  0999 V2000
   -1.7322   -0.1986    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8658    0.3006    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0002   -0.2000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.8662    0.2994    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.7318   -0.2014    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  1  0
M  END
`,
  },
  {
    id: "hexane",
    name: "hexane",
    synonyms: ["n-hexane"],
    category: "solvent",
    smiles: "CCCCCC",
    inchiKey: "VLKZOEOYAKHREP-UHFFFAOYSA-N",
    molblock: `hexane
     RDKit          2D

  6  5  0  0  0  0  0  0  0  0999 V2000
    2.1652    0.2482    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2988   -0.2510    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.4332    0.2496    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4332   -0.2496    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2988    0.2510    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1652   -0.2482    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  6  1  0
M  END
`,
  },
  {
    id: "cyclohexane",
    name: "cyclohexane",
    synonyms: [],
    category: "solvent",
    smiles: "C1CCCCC1",
    inchiKey: "XDTMQSROBMDMFD-UHFFFAOYSA-N",
    molblock: `cyclohexane
     RDKit          2D

  6  6  0  0  0  0  0  0  0  0999 V2000
   -0.8664   -0.4994    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8656    0.5006    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0008    1.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8664    0.4994    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8656   -0.5006    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0008   -1.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  6  1  0
  6  1  1  0
M  END
`,
  },
  {
    id: "acetic-acid",
    name: "acetic acid",
    synonyms: ["AcOH","ethanoic acid"],
    category: "solvent",
    smiles: "CC(=O)O",
    inchiKey: "QTBSBXVTEAMEQO-UHFFFAOYSA-N",
    molblock: `acetic acid
     RDKit          2D

  4  3  0  0  0  0  0  0  0  0999 V2000
   -0.8678   -0.4969    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000   -0.0001    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0036    0.9999    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.8642   -0.5030    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  2  0
  2  4  1  0
M  END
`,
  },
  {
    id: "formic-acid",
    name: "formic acid",
    synonyms: ["methanoic acid"],
    category: "solvent",
    smiles: "OC=O",
    inchiKey: "BDAGIHXWWSANSR-UHFFFAOYSA-N",
    molblock: `formic acid
     RDKit          2D

  3  2  0  0  0  0  0  0  0  0999 V2000
   -0.8666    0.1635    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0012   -0.3333    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8654    0.1699    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  2  0
M  END
`,
  },
  {
    id: "triethylamine",
    name: "triethylamine",
    synonyms: ["NEt3","Et3N","TEA"],
    category: "solvent",
    smiles: "CCN(CC)CC",
    inchiKey: "ZMANZCXQSJIPKH-UHFFFAOYSA-N",
    molblock: `triethylamine
     RDKit          2D

  7  6  0  0  0  0  0  0  0  0999 V2000
    1.1105    1.5021    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1125    0.5023    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2475    0.0005    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6197    0.4987    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4847   -0.0029    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2495   -0.9995    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6155   -1.5011    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  1  0
  3  6  1  0
  6  7  1  0
M  END
`,
  },
  {
    id: "benzene",
    name: "benzene",
    synonyms: [],
    category: "aromatic",
    smiles: "c1ccccc1",
    inchiKey: "UHOVQNZJYSORNB-UHFFFAOYSA-N",
    molblock: `benzene
     RDKit          2D

  6  6  0  0  0  0  0  0  0  0999 V2000
   -0.8664   -0.4994    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8656    0.5006    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0008    1.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8664    0.4994    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8656   -0.5006    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0008   -1.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  5  6  2  0
  6  1  1  0
M  END
`,
  },
  {
    id: "toluene",
    name: "toluene",
    synonyms: ["methylbenzene"],
    category: "aromatic",
    smiles: "Cc1ccccc1",
    inchiKey: "YXFVVABEGXRONW-UHFFFAOYSA-N",
    molblock: `toluene
     RDKit          2D

  7  7  0  0  0  0  0  0  0  0999 V2000
   -1.4853   -0.8560    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6189   -0.3566    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6181    0.6434    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2483    1.1426    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1139    0.6420    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1131   -0.3580    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2467   -0.8574    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  2  0
  3  4  1  0
  4  5  2  0
  5  6  1  0
  6  7  2  0
  7  2  1  0
M  END
`,
  },
  {
    id: "phenol",
    name: "phenol",
    synonyms: ["hydroxybenzene"],
    category: "aromatic",
    smiles: "Oc1ccccc1",
    inchiKey: "ISWSIDIOOBJBQZ-UHFFFAOYSA-N",
    molblock: `phenol
     RDKit          2D

  7  7  0  0  0  0  0  0  0  0999 V2000
   -1.4853   -0.8560    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6189   -0.3566    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6181    0.6434    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2483    1.1426    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1139    0.6420    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1131   -0.3580    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2467   -0.8574    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  2  0
  3  4  1  0
  4  5  2  0
  5  6  1  0
  6  7  2  0
  7  2  1  0
M  END
`,
  },
  {
    id: "aniline",
    name: "aniline",
    synonyms: ["aminobenzene","benzenamine"],
    category: "aromatic",
    smiles: "Nc1ccccc1",
    inchiKey: "PAYRUJLWNCNPSJ-UHFFFAOYSA-N",
    molblock: `aniline
     RDKit          2D

  7  7  0  0  0  0  0  0  0  0999 V2000
   -1.4853   -0.8560    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6189   -0.3566    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6181    0.6434    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2483    1.1426    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1139    0.6420    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1131   -0.3580    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2467   -0.8574    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  2  0
  3  4  1  0
  4  5  2  0
  5  6  1  0
  6  7  2  0
  7  2  1  0
M  END
`,
  },
  {
    id: "naphthalene",
    name: "naphthalene",
    synonyms: [],
    category: "aromatic",
    smiles: "c1ccc2ccccc2c1",
    inchiKey: "UFWIBTONFRDIAS-UHFFFAOYSA-N",
    molblock: `naphthalene
     RDKit          2D

 10 11  0  0  0  0  0  0  0  0999 V2000
   -1.7316    0.5014    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7324   -0.4986    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8668   -0.9994    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0004   -0.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8652   -1.0006    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.7316   -0.5014    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.7324    0.4986    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8668    0.9994    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0004    0.5000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8652    1.0006    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  5  6  2  0
  6  7  1  0
  7  8  2  0
  8  9  1  0
  9 10  2  0
 10  1  1  0
  9  4  1  0
M  END
`,
  },
  {
    id: "pyridine",
    name: "pyridine",
    synonyms: [],
    category: "aromatic",
    smiles: "c1ccncc1",
    inchiKey: "JUJWROOIHBZHMG-UHFFFAOYSA-N",
    molblock: `pyridine
     RDKit          2D

  6  6  0  0  0  0  0  0  0  0999 V2000
    0.8664    0.4994    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0008    1.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8656    0.5006    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8664   -0.4994    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0008   -1.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8656   -0.5006    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  5  6  2  0
  6  1  1  0
M  END
`,
  },
  {
    id: "pyrrole",
    name: "pyrrole",
    synonyms: ["1H-pyrrole"],
    category: "aromatic",
    smiles: "c1cc[nH]c1",
    inchiKey: "KAESVJOAVNADME-UHFFFAOYSA-N",
    molblock: `pyrrole
     RDKit          2D

  5  5  0  0  0  0  0  0  0  0999 V2000
   -0.0934    0.8455    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8330    0.1725    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4214   -0.7389    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5726   -0.6291    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.7752    0.3501    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  2  0
  3  4  1  0
  4  5  1  0
  5  1  2  0
M  END
`,
  },
  {
    id: "furan",
    name: "furan",
    synonyms: [],
    category: "aromatic",
    smiles: "c1ccoc1",
    inchiKey: "YLQBMQCUIZJEEH-UHFFFAOYSA-N",
    molblock: `furan
     RDKit          2D

  5  5  0  0  0  0  0  0  0  0999 V2000
   -0.0934    0.8455    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8330    0.1725    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4214   -0.7389    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5726   -0.6291    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.7752    0.3501    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  2  0
  3  4  1  0
  4  5  1  0
  5  1  2  0
M  END
`,
  },
  {
    id: "thiophene",
    name: "thiophene",
    synonyms: [],
    category: "aromatic",
    smiles: "c1ccsc1",
    inchiKey: "YTPLMLYBLZKORZ-UHFFFAOYSA-N",
    molblock: `thiophene
     RDKit          2D

  5  5  0  0  0  0  0  0  0  0999 V2000
   -0.0934    0.8455    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8330    0.1725    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4214   -0.7389    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5726   -0.6291    0.0000 S   0  0  0  0  0  0  0  0  0  0  0  0
    0.7752    0.3501    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  2  0
  3  4  1  0
  4  5  1  0
  5  1  2  0
M  END
`,
  },
  {
    id: "imidazole",
    name: "imidazole",
    synonyms: ["1H-imidazole"],
    category: "aromatic",
    smiles: "c1c[nH]cn1",
    inchiKey: "RAXXELZNTBOGNW-UHFFFAOYSA-N",
    molblock: `imidazole
     RDKit          2D

  5  5  0  0  0  0  0  0  0  0999 V2000
   -0.8330    0.1725    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4214   -0.7389    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5726   -0.6291    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.7752    0.3501    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0934    0.8455    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  3  4  1  0
  4  5  2  0
  5  1  1  0
M  END
`,
  },
  {
    id: "indole",
    name: "indole",
    synonyms: ["1H-indole"],
    category: "aromatic",
    smiles: "c1ccc2[nH]ccc2c1",
    inchiKey: "SIKJAQJRHWYJAI-UHFFFAOYSA-N",
    molblock: `indole
     RDKit          2D

  9 10  0  0  0  0  0  0  0  0999 V2000
    1.5374   -0.4988    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.5366    0.5012    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6702    1.0006    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1954    0.4998    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1466    0.8082    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7338   -0.0014    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1454   -0.8098    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1946   -0.5002    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6718   -0.9994    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  5  6  1  0
  6  7  2  0
  7  8  1  0
  8  9  2  0
  9  1  1  0
  8  4  1  0
M  END
`,
  },
  {
    id: "pyrimidine",
    name: "pyrimidine",
    synonyms: [],
    category: "aromatic",
    smiles: "c1cncnc1",
    inchiKey: "CZPWVGJYEJSRLH-UHFFFAOYSA-N",
    molblock: `pyrimidine
     RDKit          2D

  6  6  0  0  0  0  0  0  0  0999 V2000
    0.0008    1.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8656    0.5006    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8664   -0.4994    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0008   -1.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8656   -0.5006    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.8664    0.4994    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  5  6  2  0
  6  1  1  0
M  END
`,
  },
  {
    id: "purine",
    name: "purine",
    synonyms: ["7H-purine"],
    category: "aromatic",
    smiles: "c1ncc2[nH]cnc2n1",
    inchiKey: "KDCGOANMDULRCW-UHFFFAOYSA-N",
    molblock: `purine
     RDKit          2D

  9 10  0  0  0  0  0  0  0  0999 V2000
    1.5374   -0.4988    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.5366    0.5012    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.6702    1.0006    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1954    0.4998    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1466    0.8082    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7338   -0.0014    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1454   -0.8098    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1946   -0.5002    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6718   -0.9994    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  5  6  1  0
  6  7  2  0
  7  8  1  0
  8  9  2  0
  9  1  1  0
  8  4  1  0
M  END
`,
  },
  {
    id: "beta-d-glucopyranose",
    name: "β-D-glucopyranose",
    synonyms: ["glucose","D-glucose","dextrose","β-D-glucose","beta-D-glucose","beta-D-glucopyranose"],
    category: "sugar",
    smiles: "C([C@@H]1[C@H]([C@@H]([C@H]([C@@H](O1)O)O)O)O)O",
    inchiKey: "WQZGKKKJIJFFOK-VFUOTHLCSA-N",
    molblock: `β-D-glucopyranose
     RDKit          2D

 12 12  0  0  0  0  0  0  0  0999 V2000
   -0.0707    1.8750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0715    0.8750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7941    0.3744    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7933   -0.6256    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0731   -1.1250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9387   -0.6242    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9379    0.3758    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8051   -1.1236    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0739   -2.1250    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.6589   -1.1262    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.6605    0.8738    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9363    2.3758    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  6
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  6  1  0
  6  7  1  0
  6  8  1  6
  5  9  1  1
  4 10  1  6
  3 11  1  1
  1 12  1  0
  7  2  1  0
M  END
`,
  },
  {
    id: "alpha-d-glucopyranose",
    name: "α-D-glucopyranose",
    synonyms: ["α-D-glucose","alpha-D-glucose","alpha-D-glucopyranose"],
    category: "sugar",
    smiles: "C([C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O)O)O)O)O",
    inchiKey: "WQZGKKKJIJFFOK-DVKNGEFBSA-N",
    molblock: `α-D-glucopyranose
     RDKit          2D

 12 12  0  0  0  0  0  0  0  0999 V2000
   -0.0707    1.8750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0715    0.8750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7941    0.3744    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7933   -0.6256    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0731   -1.1250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9387   -0.6242    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9379    0.3758    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8051   -1.1236    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0739   -2.1250    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.6589   -1.1262    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.6605    0.8738    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9363    2.3758    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  6
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  6  1  0
  6  7  1  0
  6  8  1  1
  5  9  1  1
  4 10  1  6
  3 11  1  1
  1 12  1  0
  7  2  1  0
M  END
`,
  },
  {
    id: "aldehydo-d-glucose",
    name: "D-glucose (open chain)",
    synonyms: ["aldehydo-D-glucose","open-chain glucose","open chain glucose"],
    category: "sugar",
    smiles: "C([C@H]([C@H]([C@@H]([C@H](C=O)O)O)O)O)O",
    inchiKey: "GZCGUPFRVQAUEE-SLPGGIOYSA-N",
    molblock: `D-glucose (open chain)
     RDKit          2D

 12 11  0  0  0  0  0  0  0  0999 V2000
    2.1648    0.2518    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2992   -0.2490    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.4328    0.2504    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4328   -0.2504    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2992    0.2490    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1648   -0.2518    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.0312    0.2476    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.3000    1.2490    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4320   -1.2504    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.4320    1.2504    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.3000   -1.2490    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.0312   -0.2476    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  6  1  0
  6  7  2  0
  5  8  1  6
  4  9  1  6
  3 10  1  6
  2 11  1  1
  1 12  1  0
M  END
`,
  },
  {
    id: "beta-d-galactopyranose",
    name: "β-D-galactopyranose",
    synonyms: ["galactose","D-galactose","β-D-galactose","beta-D-galactose","beta-D-galactopyranose"],
    category: "sugar",
    smiles: "C([C@@H]1[C@@H]([C@@H]([C@H]([C@@H](O1)O)O)O)O)O",
    inchiKey: "WQZGKKKJIJFFOK-FPRJBGLDSA-N",
    molblock: `β-D-galactopyranose
     RDKit          2D

 12 12  0  0  0  0  0  0  0  0999 V2000
   -0.0707    1.8750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0715    0.8750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7941    0.3744    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7933   -0.6256    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0731   -1.1250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9387   -0.6242    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9379    0.3758    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8051   -1.1236    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0739   -2.1250    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.6589   -1.1262    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.6605    0.8738    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9363    2.3758    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  6
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  6  1  0
  6  7  1  0
  6  8  1  6
  5  9  1  1
  4 10  1  6
  3 11  1  6
  1 12  1  0
  7  2  1  0
M  END
`,
  },
  {
    id: "beta-d-mannopyranose",
    name: "β-D-mannopyranose",
    synonyms: ["mannose","D-mannose","β-D-mannose","beta-D-mannose","beta-D-mannopyranose"],
    category: "sugar",
    smiles: "C([C@@H]1[C@H]([C@@H]([C@@H]([C@@H](O1)O)O)O)O)O",
    inchiKey: "WQZGKKKJIJFFOK-RWOPYEJCSA-N",
    molblock: `β-D-mannopyranose
     RDKit          2D

 12 12  0  0  0  0  0  0  0  0999 V2000
   -0.0707    1.8750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0715    0.8750    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7941    0.3744    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7933   -0.6256    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0731   -1.1250    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9387   -0.6242    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9379    0.3758    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8051   -1.1236    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0739   -2.1250    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.6589   -1.1262    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.6605    0.8738    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9363    2.3758    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  6
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  6  1  0
  6  7  1  0
  6  8  1  6
  5  9  1  6
  4 10  1  6
  3 11  1  1
  1 12  1  0
  7  2  1  0
M  END
`,
  },
  {
    id: "beta-d-fructofuranose",
    name: "β-D-fructofuranose",
    synonyms: ["fructose","D-fructose","β-D-fructose","beta-D-fructose","beta-D-fructofuranose"],
    category: "sugar",
    smiles: "C([C@@H]1[C@H]([C@@H]([C@](O1)(CO)O)O)O)O",
    inchiKey: "RFSUNEUAIZKAJO-ARQDHWQXSA-N",
    molblock: `β-D-fructofuranose
     RDKit          2D

 12 12  0  0  0  0  0  0  0  0999 V2000
   -1.7872   -0.8580    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8744   -0.4494    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6684    0.5292    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3258    0.6356    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7344   -0.2772    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0074   -0.9478    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.5994    0.2246    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.4664   -0.2738    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.3238   -1.0852    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.8242    1.5026    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.3390    1.2710    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -2.5974   -0.2718    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  6
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  6  1  0
  5  7  1  0
  7  8  1  0
  5  9  1  6
  4 10  1  6
  3 11  1  1
  1 12  1  0
  6  2  1  0
M  END
`,
  },
  {
    id: "keto-d-fructose",
    name: "D-fructose (open chain)",
    synonyms: ["keto-D-fructose","open-chain fructose","open chain fructose"],
    category: "sugar",
    smiles: "C([C@H]([C@H]([C@@H](C(=O)CO)O)O)O)O",
    inchiKey: "BJHIKXHVCXFQLS-UYFOZJQFSA-N",
    molblock: `D-fructose (open chain)
     RDKit          2D

 12 11  0  0  0  0  0  0  0  0999 V2000
    2.1648    0.2518    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2992   -0.2490    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.4328    0.2504    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4328   -0.2504    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2992    0.2490    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.3000    1.2490    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1648   -0.2518    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.0312    0.2476    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4320   -1.2504    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.4320    1.2504    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.3000   -1.2490    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.0312   -0.2476    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  6  2  0
  5  7  1  0
  7  8  1  0
  4  9  1  6
  3 10  1  6
  2 11  1  1
  1 12  1  0
M  END
`,
  },
  {
    id: "beta-d-ribofuranose",
    name: "β-D-ribofuranose",
    synonyms: ["ribose","D-ribose","β-D-ribose","beta-D-ribose","beta-D-ribofuranose"],
    category: "sugar",
    smiles: "C([C@@H]1[C@H]([C@H]([C@@H](O1)O)O)O)O",
    inchiKey: "HMFHBZSHGGEWLO-TXICZTDVSA-N",
    molblock: `β-D-ribofuranose
     RDKit          2D

 10 10  0  0  0  0  0  0  0  0999 V2000
   -1.3221   -1.0579    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4539   -0.5617    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3449    0.4323    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6341    0.6357    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1303   -0.2325    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.4579   -0.9725    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.1243   -0.3415    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.0449    1.5475    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0849    1.1047    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1859   -0.5541    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  6
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  6  1  0
  5  7  1  6
  4  8  1  1
  3  9  1  1
  1 10  1  0
  6  2  1  0
M  END
`,
  },
  {
    id: "aldehydo-d-ribose",
    name: "D-ribose (open chain)",
    synonyms: ["aldehydo-D-ribose","open-chain ribose","open chain ribose"],
    category: "sugar",
    smiles: "C([C@H]([C@H]([C@H](C=O)O)O)O)O",
    inchiKey: "PYMYPHUHKUWMLA-LMVFSUKVSA-N",
    molblock: `D-ribose (open chain)
     RDKit          2D

 10  9  0  0  0  0  0  0  0  0999 V2000
   -1.7317   -0.4014    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8661    0.0994    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0003   -0.4000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8659    0.1006    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.7323   -0.3986    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.5979    0.1020    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.8651    1.1006    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0011   -1.4000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8669    1.0994    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -2.5981    0.0980    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  6  2  0
  4  7  1  1
  3  8  1  6
  2  9  1  1
  1 10  1  0
M  END
`,
  },
  {
    id: "2-deoxy-beta-d-ribofuranose",
    name: "2-deoxy-β-D-ribofuranose",
    synonyms: ["deoxyribose","2-deoxyribose","2-deoxy-D-ribose","2-deoxy-beta-D-ribose","2-deoxy-beta-D-ribofuranose"],
    category: "sugar",
    smiles: "C([C@@H]1[C@H](C[C@@H](O1)O)O)O",
    inchiKey: "PDWIQYODPROSQH-VPENINKCSA-N",
    molblock: `2-deoxy-β-D-ribofuranose
     RDKit          2D

  9  9  0  0  0  0  0  0  0  0999 V2000
    1.1985   -0.8960    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3345   -0.3926    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2337    0.6022    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7435    0.8140    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2469   -0.0500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.5807   -0.7958    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -2.2419   -0.1506    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.9795    1.2684    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.0665   -0.3996    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  1
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  6  1  0
  5  7  1  1
  3  8  1  6
  1  9  1  0
  6  2  1  0
M  END
`,
  },
  {
    id: "sucrose",
    name: "sucrose",
    synonyms: ["saccharose","table sugar","cane sugar"],
    category: "sugar",
    smiles: "C([C@@H]1[C@H]([C@@H]([C@H]([C@H](O1)O[C@]2([C@H]([C@@H]([C@H](O2)CO)O)O)CO)O)O)O)O",
    inchiKey: "CZMRCDWAGMRECN-UGDNZRGBSA-N",
    molblock: `sucrose
     RDKit          2D

 23 24  0  0  0  0  0  0  0  0999 V2000
    1.0250    3.2796    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.0186    2.2806    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.8824    1.7768    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.8812    0.7790    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.0130    0.2838    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.1466    0.7836    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.1514    1.7822    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7146    0.2904    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7300   -0.7112    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7226   -0.5988    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1372   -1.5090    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.3988   -2.1832    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.5288   -1.6912    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5104   -3.1780    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.4262   -3.5786    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -3.1160   -1.7092    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -2.2174    0.2710    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.2114   -0.6590    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7250   -1.5132    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.0562   -0.5162    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.7436    0.2744    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.7518    2.2730    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.8960    3.7736    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  6
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  6  1  0
  6  7  1  0
  6  8  1  1
  8  9  1  0
  9 10  1  0
 10 11  1  0
 11 12  1  0
 12 13  1  0
 12 14  1  6
 14 15  1  0
 11 16  1  1
 10 17  1  6
  9 18  1  1
 18 19  1  0
  5 20  1  1
  4 21  1  6
  3 22  1  1
  1 23  1  0
  7  2  1  0
 13  9  1  0
M  END
`,
  },
  {
    id: "glycine",
    name: "glycine",
    synonyms: ["Gly"],
    category: "amino-acid",
    smiles: "NCC(=O)O",
    inchiKey: "DHMQDGOQFOQNFH-UHFFFAOYSA-N",
    molblock: `glycine
     RDKit          2D

  5  4  0  0  0  0  0  0  0  0999 V2000
   -1.3856   -0.0012    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.5192   -0.5004    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3464    0.0002    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3456    1.0002    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.2128   -0.4990    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  2  0
  3  5  1  0
M  END
`,
  },
  {
    id: "l-alanine",
    name: "L-alanine",
    synonyms: ["alanine","Ala"],
    category: "amino-acid",
    smiles: "C[C@@H](C(=O)O)N",
    inchiKey: "QNAYBMKLOCPYGJ-REOHCLBHSA-N",
    molblock: `L-alanine
     RDKit          2D

  6  5  0  0  0  0  0  0  0  0999 V2000
   -0.4320    1.2504    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4328    0.2504    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.4328   -0.2504    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2992    0.2490    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.4320   -1.2504    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2992   -0.2490    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  1
  2  3  1  0
  3  4  2  0
  3  5  1  0
  2  6  1  0
M  END
`,
  },
  {
    id: "l-valine",
    name: "L-valine",
    synonyms: ["valine","Val"],
    category: "amino-acid",
    smiles: "CC(C)[C@@H](C(=O)O)N",
    inchiKey: "KZSNJWFQEVHDMF-BYPYZUCNSA-N",
    molblock: `L-valine
     RDKit          2D

  8  7  0  0  0  0  0  0  0  0999 V2000
   -1.1860    1.3168    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3218    0.8136    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5460    1.3106    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3254   -0.1864    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5388   -0.6894    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4066   -0.1926    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.5352   -1.6894    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1932   -0.6832    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  2  4  1  0
  4  5  1  0
  5  6  2  0
  5  7  1  0
  4  8  1  1
M  END
`,
  },
  {
    id: "l-leucine",
    name: "L-leucine",
    synonyms: ["leucine","Leu"],
    category: "amino-acid",
    smiles: "CC(C)C[C@@H](C(=O)O)N",
    inchiKey: "ROHFNLRQFUQHCH-YFKPBYRVSA-N",
    molblock: `L-leucine
     RDKit          2D

  9  8  0  0  0  0  0  0  0  0999 V2000
   -0.7715    2.1105    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7707    1.1105    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.6363    0.6097    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0957    0.6111    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0965   -0.3889    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.9629   -0.8881    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.8285   -0.3875    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.9637   -1.8881    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7691   -0.8895    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  2  4  1  0
  4  5  1  0
  5  6  1  0
  6  7  2  0
  6  8  1  0
  5  9  1  1
M  END
`,
  },
  {
    id: "l-isoleucine",
    name: "L-isoleucine",
    synonyms: ["isoleucine","Ile"],
    category: "amino-acid",
    smiles: "CC[C@H](C)[C@@H](C(=O)O)N",
    inchiKey: "AGPKZVBTJJNPAG-WHFBIAKZSA-N",
    molblock: `L-isoleucine
     RDKit          2D

  9  8  0  0  0  0  0  0  0  0999 V2000
   -1.0601    2.0547    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0593    1.0547    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1929    0.5555    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6727    1.0561    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1921   -0.4445    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6743   -0.9439    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.5399   -0.4431    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.6751   -1.9439    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0577   -0.9453    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  6
  3  5  1  0
  5  6  1  0
  6  7  2  0
  6  8  1  0
  5  9  1  1
M  END
`,
  },
  {
    id: "l-proline",
    name: "L-proline",
    synonyms: ["proline","Pro"],
    category: "amino-acid",
    smiles: "C1C[C@H](NC1)C(=O)O",
    inchiKey: "ONIBWKKTOPOVIA-BYPYZUCNSA-N",
    molblock: `L-proline
     RDKit          2D

  8  8  0  0  0  0  0  0  0  0999 V2000
   -1.1146    1.1312    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1270    0.9734    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0282   -0.0144    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8634   -0.4672    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5696    0.2406    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.9186   -0.4694    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.7578    0.0742    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.9698   -1.4682    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  1  0
  3  6  1  1
  6  7  2  0
  6  8  1  0
  5  1  1  0
M  END
`,
  },
  {
    id: "l-phenylalanine",
    name: "L-phenylalanine",
    synonyms: ["phenylalanine","Phe"],
    category: "amino-acid",
    smiles: "c1ccc(cc1)C[C@@H](C(=O)O)N",
    inchiKey: "COLNVLDHVKWLRT-QMMMGPOBSA-N",
    molblock: `L-phenylalanine
     RDKit          2D

 12 12  0  0  0  0  0  0  0  0999 V2000
   -1.9498    1.6235    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0842    2.1241    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2178    1.6249    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2170    0.6247    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0826    0.1243    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.9490    0.6235    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6494    0.1255    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6502   -0.8745    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.5166   -1.3737    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.3822   -0.8731    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.5174   -2.3737    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2154   -1.3751    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  5  6  2  0
  4  7  1  0
  7  8  1  0
  8  9  1  0
  9 10  2  0
  9 11  1  0
  8 12  1  1
  6  1  1  0
M  END
`,
  },
  {
    id: "l-tryptophan",
    name: "L-tryptophan",
    synonyms: ["tryptophan","Trp"],
    category: "amino-acid",
    smiles: "c1ccc2c(c1)c(c[nH]2)C[C@@H](C(=O)O)N",
    inchiKey: "QIVBCDIJIAJPQS-VIFPVBQESA-N",
    molblock: `L-tryptophan
     RDKit          2D

 15 16  0  0  0  0  0  0  0  0999 V2000
   -1.8861   -0.7621    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.5537   -0.0173    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.2425    0.9329    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2639    1.1387    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.5965    0.3941    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9077   -0.5563    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3181    0.7987    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2155    1.7933    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7619    2.0037    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    1.1829    0.2967    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1805   -0.7033    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.0455   -1.2053    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.9127   -0.7071    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.0431   -2.2053    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.3133   -1.2013    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  5  6  2  0
  5  7  1  0
  7  8  2  0
  8  9  1  0
  7 10  1  0
 10 11  1  0
 11 12  1  0
 12 13  2  0
 12 14  1  0
 11 15  1  1
  6  1  1  0
  9  4  1  0
M  END
`,
  },
  {
    id: "l-methionine",
    name: "L-methionine",
    synonyms: ["methionine","Met"],
    category: "amino-acid",
    smiles: "CSCC[C@@H](C(=O)O)N",
    inchiKey: "FFEARJCKVFRZRR-BYPYZUCNSA-N",
    molblock: `L-methionine
     RDKit          2D

  9  8  0  0  0  0  0  0  0  0999 V2000
   -1.6377    2.3876    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7713    1.8882    0.0000 S   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7705    0.8882    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0959    0.3890    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0967   -0.6110    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.9631   -1.1104    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.8287   -0.6096    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.9639   -2.1104    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7689   -1.1118    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  6  1  0
  6  7  2  0
  6  8  1  0
  5  9  1  1
M  END
`,
  },
  {
    id: "l-serine",
    name: "L-serine",
    synonyms: ["serine","Ser"],
    category: "amino-acid",
    smiles: "C([C@@H](C(=O)O)N)O",
    inchiKey: "MTCFGRXMJLQNBG-REOHCLBHSA-N",
    molblock: `L-serine
     RDKit          2D

  7  6  0  0  0  0  0  0  0  0999 V2000
   -0.2482    0.9999    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2474   -0.0001    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6190   -0.4995    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4846    0.0013    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.6198   -1.4995    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1130   -0.5009    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1146    1.4991    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  2  0
  3  5  1  0
  2  6  1  1
  1  7  1  0
M  END
`,
  },
  {
    id: "l-threonine",
    name: "L-threonine",
    synonyms: ["threonine","Thr"],
    category: "amino-acid",
    smiles: "C[C@H]([C@@H](C(=O)O)N)O",
    inchiKey: "AYFVYJQAPQTCCC-GBXIJSLDSA-N",
    molblock: `L-threonine
     RDKit          2D

  8  7  0  0  0  0  0  0  0  0999 V2000
   -1.1935    1.3101    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3264    0.8119    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3244   -0.1881    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5426   -0.6863    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4077   -0.1847    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.5447   -1.6863    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1894   -0.6899    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.5387    1.3135    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  1
  2  3  1  0
  3  4  1  0
  4  5  2  0
  4  6  1  0
  3  7  1  1
  2  8  1  0
M  END
`,
  },
  {
    id: "l-cysteine",
    name: "L-cysteine",
    synonyms: ["cysteine","Cys"],
    category: "amino-acid",
    smiles: "C([C@@H](C(=O)O)N)S",
    inchiKey: "XUJNEKJLAYXESH-REOHCLBHSA-N",
    molblock: `L-cysteine
     RDKit          2D

  7  6  0  0  0  0  0  0  0  0999 V2000
   -0.2482    0.9999    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2474   -0.0001    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6190   -0.4995    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4846    0.0013    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.6198   -1.4995    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1130   -0.5009    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -1.1146    1.4991    0.0000 S   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  2  0
  3  5  1  0
  2  6  1  1
  1  7  1  0
M  END
`,
  },
  {
    id: "l-tyrosine",
    name: "L-tyrosine",
    synonyms: ["tyrosine","Tyr"],
    category: "amino-acid",
    smiles: "c1cc(ccc1C[C@@H](C(=O)O)N)O",
    inchiKey: "OUYCCCASQSFEME-QMMMGPOBSA-N",
    molblock: `L-tyrosine
     RDKit          2D

 13 13  0  0  0  0  0  0  0  0999 V2000
   -0.8660   -0.0390    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7324    0.4602    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7332    1.4602    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8676    1.9608    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0012    1.4616    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0004    0.4614    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8660   -0.0378    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8668   -1.0378    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.7332   -1.5370    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.5988   -1.0364    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.7340   -2.5370    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0012   -1.5384    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -2.5996    1.9594    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  5  6  2  0
  6  7  1  0
  7  8  1  0
  8  9  1  0
  9 10  2  0
  9 11  1  0
  8 12  1  1
  3 13  1  0
  6  1  1  0
M  END
`,
  },
  {
    id: "l-asparagine",
    name: "L-asparagine",
    synonyms: ["asparagine","Asn"],
    category: "amino-acid",
    smiles: "C([C@@H](C(=O)O)N)C(=O)N",
    inchiKey: "DCXYFEDJOCDNAF-REOHCLBHSA-N",
    molblock: `L-asparagine
     RDKit          2D

  9  8  0  0  0  0  0  0  0  0999 V2000
    0.0957    0.6111    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0965   -0.3889    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.9629   -0.8881    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.8285   -0.3875    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.9637   -1.8881    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7691   -0.8895    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7707    1.1105    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.6363    0.6097    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7715    2.1105    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  2  0
  3  5  1  0
  2  6  1  1
  1  7  1  0
  7  8  2  0
  7  9  1  0
M  END
`,
  },
  {
    id: "l-glutamine",
    name: "L-glutamine",
    synonyms: ["glutamine","Gln"],
    category: "amino-acid",
    smiles: "C(CC(=O)N)[C@@H](C(=O)O)N",
    inchiKey: "ZDXPYRJPNDTMRX-VKHMYHEASA-N",
    molblock: `L-glutamine
     RDKit          2D

 10  9  0  0  0  0  0  0  0  0999 V2000
    0.0865    0.1500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7799    0.6494    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7807    1.6494    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0849    2.1500    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.6471    2.1486    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.0873   -0.8500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.9537   -1.3492    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.8193   -0.8486    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.9545   -2.3492    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7783   -1.3506    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  2  0
  3  5  1  0
  1  6  1  0
  6  7  1  0
  7  8  2  0
  7  9  1  0
  6 10  1  1
M  END
`,
  },
  {
    id: "l-aspartic-acid",
    name: "L-aspartic acid",
    synonyms: ["aspartic acid","aspartate","Asp"],
    category: "amino-acid",
    smiles: "C([C@@H](C(=O)O)N)C(=O)O",
    inchiKey: "CKLJMWTZIZZHCS-REOHCLBHSA-N",
    molblock: `L-aspartic acid
     RDKit          2D

  9  8  0  0  0  0  0  0  0  0999 V2000
    0.0957    0.6111    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0965   -0.3889    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.9629   -0.8881    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.8285   -0.3875    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.9637   -1.8881    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7691   -0.8895    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7707    1.1105    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.6363    0.6097    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7715    2.1105    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  2  0
  3  5  1  0
  2  6  1  1
  1  7  1  0
  7  8  2  0
  7  9  1  0
M  END
`,
  },
  {
    id: "l-glutamic-acid",
    name: "L-glutamic acid",
    synonyms: ["glutamic acid","glutamate","Glu"],
    category: "amino-acid",
    smiles: "C(CC(=O)O)[C@@H](C(=O)O)N",
    inchiKey: "WHUUTDBJXJRKMK-VKHMYHEASA-N",
    molblock: `L-glutamic acid
     RDKit          2D

 10  9  0  0  0  0  0  0  0  0999 V2000
    0.0865    0.1500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7799    0.6494    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7807    1.6494    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0849    2.1500    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.6471    2.1486    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.0873   -0.8500    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.9537   -1.3492    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.8193   -0.8486    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.9545   -2.3492    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.7783   -1.3506    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  2  0
  3  5  1  0
  1  6  1  0
  6  7  1  0
  7  8  2  0
  7  9  1  0
  6 10  1  1
M  END
`,
  },
  {
    id: "l-lysine",
    name: "L-lysine",
    synonyms: ["lysine","Lys"],
    category: "amino-acid",
    smiles: "C(CCN)C[C@@H](C(=O)O)N",
    inchiKey: "KDXKERNSBIXSRK-YFKPBYRVSA-N",
    molblock: `L-lysine
     RDKit          2D

 10  9  0  0  0  0  0  0  0  0999 V2000
   -0.6066    0.5496    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6074    1.5496    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4738    2.0488    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4746    3.0488    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.2598    0.0502    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2606   -0.9498    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1270   -1.4492    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.9926   -0.9484    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.1278   -2.4492    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6050   -1.4504    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  1  5  1  0
  5  6  1  0
  6  7  1  0
  7  8  2  0
  7  9  1  0
  6 10  1  1
M  END
`,
  },
  {
    id: "l-arginine",
    name: "L-arginine",
    synonyms: ["arginine","Arg"],
    category: "amino-acid",
    smiles: "C(C[C@@H](C(=O)O)N)CN=C(N)N",
    inchiKey: "ODKSFYDXXFIFQN-BYPYZUCNSA-N",
    molblock: `L-arginine
     RDKit          2D

 12 11  0  0  0  0  0  0  0  0999 V2000
   -0.3608   -0.0420    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5056   -0.5412    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5064   -1.5412    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.3728   -2.0406    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.2384   -1.5400    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.3736   -3.0406    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3592   -2.0420    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3616    0.9580    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2280    1.4574    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2288    2.4574    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3632    2.9580    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -2.0952    2.9566    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  2  0
  4  6  1  0
  3  7  1  1
  1  8  1  0
  8  9  1  0
  9 10  2  0
 10 11  1  0
 10 12  1  0
M  END
`,
  },
  {
    id: "l-histidine",
    name: "L-histidine",
    synonyms: ["histidine","His"],
    category: "amino-acid",
    smiles: "c1c(nc[nH]1)C[C@@H](C(=O)O)N",
    inchiKey: "HNDVDQJCIGZPNO-YFKPBYRVSA-N",
    molblock: `L-histidine
     RDKit          2D

 11 11  0  0  0  0  0  0  0  0999 V2000
   -1.2859    0.3593    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3707    0.7627    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4713    1.7575    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4487    1.9693    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.9519    1.1053    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.4933    0.2591    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.4893   -0.7407    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.3533   -1.2441    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.2215   -0.7477    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.3493   -2.2439    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3787   -1.2371    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  2  6  1  0
  6  7  1  0
  7  8  1  0
  8  9  2  0
  8 10  1  0
  7 11  1  1
  5  1  1  0
M  END
`,
  },
  {
    id: "adenine",
    name: "adenine",
    synonyms: [],
    category: "nucleobase",
    smiles: "Nc1ncnc2[nH]cnc12",
    inchiKey: "GFFGJBXGBJISGV-UHFFFAOYSA-N",
    molblock: `adenine
     RDKit          2D

 10 11  0  0  0  0  0  0  0  0999 V2000
    0.6024    1.8005    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.6032    0.8005    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4696    0.3011    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    1.4704   -0.6989    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6048   -1.1995    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2616   -0.7001    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2124   -1.0099    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8008   -0.2015    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2136    0.6081    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2624    0.2999    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  2  0
  3  4  1  0
  4  5  2  0
  5  6  1  0
  6  7  1  0
  7  8  1  0
  8  9  2  0
  9 10  1  0
 10  2  1  0
 10  6  2  0
M  END
`,
  },
  {
    id: "guanine",
    name: "guanine",
    synonyms: [],
    category: "nucleobase",
    smiles: "Nc1nc2[nH]cnc2c(=O)[nH]1",
    inchiKey: "UYTPUPDQBNUYGX-UHFFFAOYSA-N",
    molblock: `guanine
     RDKit          2D

 11 12  0  0  0  0  0  0  0  0999 V2000
    2.0029   -1.2991    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    1.1917   -0.7145    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2797   -1.1247    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.5315   -0.5401    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5089   -0.7519    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -2.0123    0.1121    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.3459    0.8579    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4309    0.4547    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.4811    0.8651    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5817    1.8599    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.2923    0.2805    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  2  0
  3  4  1  0
  4  5  1  0
  5  6  1  0
  6  7  2  0
  7  8  1  0
  8  9  1  0
  9 10  2  0
  9 11  1  0
 11  2  1  0
  8  4  2  0
M  END
`,
  },
  {
    id: "cytosine",
    name: "cytosine",
    synonyms: [],
    category: "nucleobase",
    smiles: "Nc1cc[nH]c(=O)n1",
    inchiKey: "OPTASPLRGRRNAP-UHFFFAOYSA-N",
    molblock: `cytosine
     RDKit          2D

  8  8  0  0  0  0  0  0  0  0999 V2000
   -1.5164   -1.1237    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6500   -0.6245    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2156   -1.1251    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.0820   -0.6259    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.0828    0.3741    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.2172    0.8749    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2180    1.8749    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6492    0.3755    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  5  6  1  0
  6  7  2  0
  6  8  1  0
  8  2  2  0
M  END
`,
  },
  {
    id: "thymine",
    name: "thymine",
    synonyms: ["5-methyluracil"],
    category: "nucleobase",
    smiles: "Cc1c[nH]c(=O)[nH]c1=O",
    inchiKey: "RWQNBRDOKXIBIV-UHFFFAOYSA-N",
    molblock: `thymine
     RDKit          2D

  9  9  0  0  0  0  0  0  0  0999 V2000
    1.5387   -1.1124    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.6731   -0.6116    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1933   -1.1110    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0589   -0.6104    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -1.0581    0.3896    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.9237    0.8904    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1917    0.8890    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.6739    0.3884    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.5403    0.8876    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  2  0
  3  4  1  0
  4  5  1  0
  5  6  2  0
  5  7  1  0
  7  8  1  0
  8  9  2  0
  8  2  1  0
M  END
`,
  },
  {
    id: "uracil",
    name: "uracil",
    synonyms: [],
    category: "nucleobase",
    smiles: "O=c1cc[nH]c(=O)[nH]1",
    inchiKey: "ISAKRJDGNUQOIC-UHFFFAOYSA-N",
    molblock: `uracil
     RDKit          2D

  8  8  0  0  0  0  0  0  0  0999 V2000
   -1.5164   -1.1237    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6500   -0.6245    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2156   -1.1251    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.0820   -0.6259    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.0828    0.3741    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.2172    0.8749    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2180    1.8749    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6492    0.3755    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  2  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  5  6  1  0
  6  7  2  0
  6  8  1  0
  8  2  1  0
M  END
`,
  },
  {
    id: "urea",
    name: "urea",
    synonyms: ["carbamide"],
    category: "biomolecule",
    smiles: "NC(N)=O",
    inchiKey: "XSQUKJJJFZCRTK-UHFFFAOYSA-N",
    molblock: `urea
     RDKit          2D

  4  3  0  0  0  0  0  0  0  0999 V2000
    0.0020   -1.0000    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8670    0.4982    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.8650    0.5018    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  2  4  2  0
M  END
`,
  },
  {
    id: "glycerol",
    name: "glycerol",
    synonyms: ["glycerin","propane-1,2,3-triol"],
    category: "biomolecule",
    smiles: "OCC(O)CO",
    inchiKey: "PEDCQBHIVMGVHV-UHFFFAOYSA-N",
    molblock: `glycerol
     RDKit          2D

  6  5  0  0  0  0  0  0  0  0999 V2000
    1.7320   -0.0014    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.8656   -0.5006    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0000   -0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0008    1.0000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8664   -0.4994    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7320    0.0014    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  3  5  1  0
  5  6  1  0
M  END
`,
  },
  {
    id: "citric-acid",
    name: "citric acid",
    synonyms: ["citrate"],
    category: "biomolecule",
    smiles: "OC(=O)CC(O)(CC(=O)O)C(=O)O",
    inchiKey: "KRKNYBCHXYNGOX-UHFFFAOYSA-N",
    molblock: `citric acid
     RDKit          2D

 13 12  0  0  0  0  0  0  0  0999 V2000
   -0.2720    2.1523    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.2280    1.2863    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2280    1.2863    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.2720    0.4203    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.2280   -0.4457    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7280    0.4203    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6380   -0.9457    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5040   -0.4457    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5040    0.5543    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -2.3700   -0.9457    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.0940   -0.9457    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.0940   -1.9457    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.9600   -0.4457    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  2  0
  2  4  1  0
  4  5  1  0
  5  6  1  0
  5  7  1  0
  7  8  1  0
  8  9  2  0
  8 10  1  0
  5 11  1  0
 11 12  2  0
 11 13  1  0
M  END
`,
  },
  {
    id: "dopamine",
    name: "dopamine",
    synonyms: [],
    category: "biomolecule",
    smiles: "NCCc1ccc(O)c(O)c1",
    inchiKey: "VYFYYTLLBUKUHU-UHFFFAOYSA-N",
    molblock: `dopamine
     RDKit          2D

 11 11  0  0  0  0  0  0  0  0999 V2000
   -3.0675   -0.7837    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -2.2033   -0.2805    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.3355   -0.7775    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4715   -0.2743    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4749    0.7255    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3893    1.2287    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2571    0.7319    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.1213    1.2349    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.2605   -0.2681    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.1285   -0.7651    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.3965   -0.7713    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  2  0
  5  6  1  0
  6  7  2  0
  7  8  1  0
  7  9  1  0
  9 10  1  0
  9 11  2  0
 11  4  1  0
M  END
`,
  },
  {
    id: "serotonin",
    name: "serotonin",
    synonyms: ["5-hydroxytryptamine","5-HT"],
    category: "biomolecule",
    smiles: "NCCc1c[nH]c2ccc(O)cc12",
    inchiKey: "QZAYGJVTTNCVMB-UHFFFAOYSA-N",
    molblock: `serotonin
     RDKit          2D

 13 14  0  0  0  0  0  0  0  0999 V2000
    2.4189    2.3288    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    2.1091    1.3782    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1307    1.1710    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8211    0.2202    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.4079   -0.5894    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8199   -1.3980    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1311   -1.0880    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9975   -1.5874    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8631   -1.0868    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8623   -0.0866    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.7279    0.4140    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9959    0.4126    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.1303   -0.0882    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  2  0
  5  6  1  0
  6  7  1  0
  7  8  2  0
  8  9  1  0
  9 10  2  0
 10 11  1  0
 10 12  1  0
 12 13  2  0
 13  4  1  0
 13  7  1  0
M  END
`,
  },
  {
    id: "adrenaline",
    name: "(R)-adrenaline",
    synonyms: ["adrenaline","epinephrine","(R)-epinephrine"],
    category: "biomolecule",
    smiles: "CNC[C@H](O)c1ccc(O)c(O)c1",
    inchiKey: "UCTWMZQNUQWSLP-VIFPVBQESA-N",
    molblock: `(R)-adrenaline
     RDKit          2D

 13 13  0  0  0  0  0  0  0  0999 V2000
   -3.5302    0.1280    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.6624    0.6248    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7982    0.1218    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9304    0.6186    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9268    1.6186    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0662    0.1156    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0698   -0.8844    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7944   -1.3876    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.6622   -0.8906    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.5264   -1.3936    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.6658    0.1094    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.5336    0.6062    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.8016    0.6126    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  1  6
  4  6  1  0
  6  7  2  0
  7  8  1  0
  8  9  2  0
  9 10  1  0
  9 11  1  0
 11 12  1  0
 11 13  2  0
 13  6  1  0
M  END
`,
  },
  {
    id: "cholesterol",
    name: "cholesterol",
    synonyms: [],
    category: "biomolecule",
    smiles: "C[C@H](CCCC(C)C)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2CC=C4[C@@]3(CC[C@@H](C4)O)C)C",
    inchiKey: "HVYWMOMLDIMFJA-DPAQBDIFSA-N",
    molblock: `cholesterol
     RDKit          2D

 28 31  0  0  0  0  0  0  0  0999 V2000
    2.1381   -0.9196    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.1405    0.0806    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.0077    0.5786    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    3.8725    0.0766    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    4.7397    0.5746    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.6047    0.0728    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    6.4719    0.5708    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    5.6023   -0.9274    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2757    0.5824    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1731    1.5770    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.1957    1.7874    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.3063    0.9224    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.3611    0.1778    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0499   -0.7726    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9285   -0.9784    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5961   -0.2336    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2847    0.7166    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.9523    1.4614    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.9309    1.2556    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.2421    0.3054    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.5745   -0.4394    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.8857   -1.3896    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -3.8643   -1.5954    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.5319   -0.8508    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -4.2205    0.0996    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -5.5103   -1.0564    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -1.9071   -1.1840    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1027   -0.4928    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  2  1  1  1
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  6  1  0
  6  7  1  0
  6  8  1  0
  2  9  1  0
  9 10  1  6
 10 11  1  0
 12 11  1  6
 12 13  1  0
 13 14  1  0
 14 15  1  0
 16 15  1  6
 16 17  1  0
 17 18  1  1
 18 19  1  0
 19 20  2  0
 20 21  1  0
 21 22  1  0
 22 23  1  0
 23 24  1  0
 24 25  1  0
 24 26  1  6
 21 27  1  6
 13 28  1  6
 13  9  1  0
 17 12  1  0
 21 16  1  0
 25 20  1  0
M  END
`,
  },
  {
    id: "caffeine",
    name: "caffeine",
    synonyms: ["1,3,7-trimethylxanthine"],
    category: "drug",
    smiles: "Cn1cnc2c1c(=O)n(C)c(=O)n2C",
    inchiKey: "RYYVLZVUVIJVGH-UHFFFAOYSA-N",
    molblock: `caffeine
     RDKit          2D

 14 15  0  0  0  0  0  0  0  0999 V2000
   -1.6167   -1.8062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.4049   -0.8288    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -2.0711   -0.0832    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5677    0.7808    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.5905    0.5692    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4899   -0.4258    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.4221   -0.8360    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5227   -1.8310    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.2333   -0.2514    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    2.1453   -0.6618    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.1327    0.7434    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.9439    1.3280    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.2207    1.1538    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    0.1201    2.1486    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  2  0
  4  5  1  0
  5  6  2  0
  6  7  1  0
  7  8  2  0
  7  9  1  0
  9 10  1  0
  9 11  1  0
 11 12  2  0
 11 13  1  0
 13 14  1  0
  6  2  1  0
 13  5  1  0
M  END
`,
  },
  {
    id: "aspirin",
    name: "aspirin",
    synonyms: ["acetylsalicylic acid","ASA"],
    category: "drug",
    smiles: "CC(=O)Oc1ccccc1C(=O)O",
    inchiKey: "BSYNRYMUTXBXSQ-UHFFFAOYSA-N",
    molblock: `aspirin
     RDKit          2D

 13 13  0  0  0  0  0  0  0  0999 V2000
   -2.6640    0.3130    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.7990   -0.1888    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8012   -1.1888    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9320    0.3096    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0672   -0.1922    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0690   -1.1922    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7960   -1.6940    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.6630   -1.1956    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.6650   -0.1956    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8000    0.3062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.8020    1.3060    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0630    1.8078    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    1.6690    1.8042    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  2  0
  2  4  1  0
  4  5  1  0
  5  6  2  0
  6  7  1  0
  7  8  2  0
  8  9  1  0
  9 10  2  0
 10 11  1  0
 11 12  2  0
 11 13  1  0
 10  5  1  0
M  END
`,
  },
  {
    id: "salicylic-acid",
    name: "salicylic acid",
    synonyms: ["2-hydroxybenzoic acid"],
    category: "drug",
    smiles: "OC(=O)c1ccccc1O",
    inchiKey: "YGSDEFSMJLZEOE-UHFFFAOYSA-N",
    molblock: `salicylic acid
     RDKit          2D

 10 10  0  0  0  0  0  0  0  0999 V2000
    1.0426    1.6978    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.1756    1.1996    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6894    1.7014    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.1736    0.1996    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.0386   -0.3020    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.0366   -1.3020    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.1696   -1.8004    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6954   -1.2986    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.6934   -0.2986    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.5584    0.2032    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  2  0
  2  4  1  0
  4  5  2  0
  5  6  1  0
  6  7  2  0
  7  8  1  0
  8  9  2  0
  9 10  1  0
  9  4  1  0
M  END
`,
  },
  {
    id: "paracetamol",
    name: "paracetamol",
    synonyms: ["acetaminophen","APAP"],
    category: "drug",
    smiles: "CC(=O)Nc1ccc(O)cc1",
    inchiKey: "RZVAJINKPMORJF-UHFFFAOYSA-N",
    molblock: `paracetamol
     RDKit          2D

 11 11  0  0  0  0  0  0  0  0999 V2000
   -2.6735   -0.9186    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8093   -0.4156    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.8129    0.5844    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.9415   -0.9124    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0773   -0.4094    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.7905   -0.9062    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.6547   -0.4030    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.6511    0.5968    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.5153    1.1000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    0.7833    1.0938    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0809    0.5906    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  2  0
  2  4  1  0
  4  5  1  0
  5  6  2  0
  6  7  1  0
  7  8  2  0
  8  9  1  0
  8 10  1  0
 10 11  2  0
 11  5  1  0
M  END
`,
  },
  {
    id: "ibuprofen",
    name: "ibuprofen",
    synonyms: [],
    category: "drug",
    smiles: "CC(C)Cc1ccc(cc1)C(C)C(=O)O",
    inchiKey: "HEFNNWSXXWATRW-UHFFFAOYSA-N",
    molblock: `ibuprofen
     RDKit          2D

 15 15  0  0  0  0  0  0  0  0999 V2000
   -3.4074   -1.4305    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.5410   -0.9313    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.5402    0.0687    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.6754   -1.4319    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8092   -0.9327    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0566   -1.4333    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.9230   -0.9341    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.9238    0.0661    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.0582    0.5665    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8084    0.0673    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.7902    0.5653    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    2.6558    0.0645    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.7910    1.5653    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.9254    2.0659    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    2.6574    2.0645    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  2  4  1  0
  4  5  1  0
  5  6  2  0
  6  7  1  0
  7  8  2  0
  8  9  1  0
  9 10  2  0
  8 11  1  0
 11 12  1  0
 11 13  1  0
 13 14  2  0
 13 15  1  0
 10  5  1  0
M  END
`,
  },
  {
    id: "nicotine",
    name: "(S)-nicotine",
    synonyms: ["nicotine"],
    category: "drug",
    smiles: "CN1CCC[C@H]1c1cccnc1",
    inchiKey: "SNICXCGAKADSCV-JTQLQIEISA-N",
    molblock: `(S)-nicotine
     RDKit          2D

 12 13  0  0  0  0  0  0  0  0999 V2000
    1.5860   -0.9486    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.3792    0.0299    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
    2.0492    0.7723    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.5502    1.6388    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.5718    1.4320    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    0.4662    0.4377    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4004   -0.0613    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2658    0.4397    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1326   -0.0594    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -2.1336   -1.0593    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -1.2682   -1.5603    0.0000 N   0  0  0  0  0  0  0  0  0  0  0  0
   -0.4016   -1.0614    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  1  0
  3  4  1  0
  4  5  1  0
  5  6  1  0
  6  7  1  6
  7  8  2  0
  8  9  1  0
  9 10  2  0
 10 11  1  0
 11 12  2  0
  6  2  1  0
 12  7  1  0
M  END
`,
  },
];
