/**
 * Sugar perception, carbohydrate numbering, D/L, alpha/beta and the
 * ring-chain edit, on real molecules.
 *
 * Every molecule comes from a checked-in molblock generated by RDKit from
 * PubChem's SMILES (test/fixtures/projection, test/fixtures/sugar) or from
 * the structure dictionary, whose rows the build script checks against RDKit.
 * Nothing here is a hand-typed coordinate. Each D/L and alpha/beta assertion
 * first asserts that the centres it rests on resolve to R or S, because an
 * undetermined centre survives every reading and would make the assertion
 * pass while proving nothing.
 */

import { readdirSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { dictionaryEntryById } from "./dictionary.js";
import { duplicateFragment } from "./fragment.js";
import { buildMolecule } from "./builders.js";
import { addAtom, addBond, bondBetween, bondsAt, otherEnd } from "./molecule.js";
import { readMolblock } from "./molblock-read.js";
import { invertStereocentre, setBondStereo, setElement, setExplicitHydrogenCount, updateBond } from "./ops.js";
import { isRingAtom } from "./rings.js";
import { species } from "./species.js";
import { compareIds } from "./selection.js";
import { cipDescriptor, stereocenterAtoms, stereoGroupCoverage } from "./stereo.js";
import { stereoGroupAt, stereoGroupsOf, withStereoGroups } from "./stereo-groups.js";
import { ligandRefs, parityAgainst, stereoConfig, stereoTopology } from "./stereo-config.js";
import {
  anomericConfiguration,
  anomericReferenceAtom,
  carbohydrateLocant,
  carbohydrateOfRing,
  carbohydrates,
  carbohydrateSeries,
  configurationalAtom,
  cycliseSugar,
  openRing,
  perceiveSugarRing,
  sugarPerceptionComputationCount,
  sugarRings,
  type Anomer,
  type Carbohydrate,
} from "./sugar.js";
import { rotateAtoms, translateAtoms } from "./transform.js";
import type { AtomId, Molecule } from "./types.js";
import { valenceIssues } from "./valence.js";

const FIXTURES = join(dirname(fileURLToPath(import.meta.url)), "..", "test", "fixtures");

function fixture(dir: "projection" | "sugar", file: string): Molecule {
  return readMolblock(readFileSync(join(FIXTURES, dir, file), "utf8")).molecule;
}

function dictionary(id: string): Molecule {
  const entry = dictionaryEntryById(id);
  if (entry === undefined) throw new Error(`no dictionary entry ${id}`);
  return readMolblock(entry.molblock).molecule;
}

const glucoseOpen = (): Molecule => fixture("projection", "d-glucose-open.mol");

/** The only carbohydrate of a one-sugar molecule. */
function only(mol: Molecule): Carbohydrate {
  const units = carbohydrates(mol);
  expect(units).toHaveLength(1);
  return units[0]!;
}

function atLocant(unit: Carbohydrate, locant: string): AtomId {
  const id = unit.backbone.find((atom) => carbohydrateLocant(unit, atom) === locant);
  if (id === undefined) throw new Error(`no atom at locant ${locant}`);
  return id;
}

function neighbours(mol: Molecule, atomId: AtomId): AtomId[] {
  return bondsAt(mol, atomId).map((bond) => otherEnd(bond, atomId));
}

function oxygenOn(mol: Molecule, atomId: AtomId): AtomId {
  const found = neighbours(mol, atomId).filter((id) => mol.atoms[id]!.element === "O");
  expect(found).toHaveLength(1);
  return found[0]!;
}

/** R/S by locant: the letters PubChem's names give, keyed the carbohydrate way. */
function lettersByLocant(mol: Molecule, unit: Carbohydrate): Record<string, string> {
  const out: Record<string, string> = {};
  for (const id of unit.backbone) {
    const descriptor = cipDescriptor(mol, id);
    if (descriptor !== undefined) out[carbohydrateLocant(unit, id)!] = descriptor.kind;
  }
  return out;
}

/** Every stereocentre on the chain has a letter: nothing below is vacuous. */
function expectResolved(mol: Molecule, unit: Carbohydrate): void {
  for (const id of [...unit.backbone, ...unit.beyondTie]) {
    const descriptor = cipDescriptor(mol, id);
    if (descriptor === undefined) continue;
    expect(["R", "S"], `${id} resolves`).toContain(descriptor.kind);
  }
}

/** Every drawn wedge or hash swapped: the enantiomer, same picture. */
function enantiomer(mol: Molecule): Molecule {
  let next = mol;
  for (const centre of stereoTopology(mol).centres) next = invertStereocentre(next, centre.atomId);
  return next;
}

/** Atoms and bonds with orders, independent of bond direction. */
function constitution(mol: Molecule): { atoms: string[]; bonds: string[] } {
  return {
    atoms: mol.atomIds.map((id) => `${id}:${mol.atoms[id]!.element}${mol.atoms[id]!.charge}`).sort(),
    bonds: mol.bondIds
      .map((id) => {
        const bond = mol.bonds[id]!;
        return `${[bond.from, bond.to].sort().join("-")}:${bond.order}`;
      })
      .sort(),
  };
}

/** Each centre's parity against a FIXED order: its canonical ligands in `reference`. */
function paritiesAgainst(reference: Molecule, mol: Molecule): Record<AtomId, number | undefined> {
  const config = stereoConfig(mol);
  const out: Record<AtomId, number | undefined> = {};
  for (const centre of stereoConfig(reference).centres) {
    const now = config.centres.find((c) => c.atomId === centre.atomId);
    out[centre.atomId] = now === undefined ? undefined : parityAgainst(now, ligandRefs(centre));
  }
  return out;
}

// ---------------------------------------------------------------------------
// Sugar rings
// ---------------------------------------------------------------------------

describe("sugar rings", () => {
  it("finds a pyranose's anomeric carbon by its bond to the ring oxygen, not by its OH", () => {
    const mol = fixture("projection", "beta-d-glucopyranose.mol");
    const [perceived] = sugarRings(mol);
    expect(perceived?.kind).toBe("sugarRing");
    if (perceived?.kind !== "sugarRing") return;
    const ring = perceived.ring;
    expect(ring.form).toBe("pyranose");
    expect(mol.atoms[ring.ringHeteroatom]!.element).toBe("O");
    // C1 and C2..C4 all carry an OH; only C1 is also bonded to the ring O.
    const ringCarbonsWithOH = ring.ringAtomIds.filter(
      (id) =>
        id !== ring.ringHeteroatom &&
        neighbours(mol, id).some((o) => mol.atoms[o]!.element === "O" && !ring.ringAtomIds.includes(o)),
    );
    expect(ringCarbonsWithOH).toHaveLength(4);
    expect(neighbours(mol, ring.anomericCarbon)).toContain(ring.ringHeteroatom);
    expect(mol.atoms[ring.anomericSubstituent]!.element).toBe("O");
    expect(ring.ringAtomIds[0]).toBe(ring.ringHeteroatom);
    expect(ring.ringAtomIds[1]).toBe(ring.anomericCarbon);
    // The ring-closing carbon is the one carrying C6.
    expect(neighbours(mol, ring.ringClosingCarbon).some((id) => mol.atoms[id]!.element === "C" && !ring.ringAtomIds.includes(id))).toBe(true);
  });

  it("takes a nucleoside's N9 as the anomeric substituent", () => {
    for (const mol of [fixture("projection", "adenosine.mol"), fixture("sugar", "2-deoxyadenosine.mol")]) {
      const [perceived] = sugarRings(mol);
      if (perceived?.kind !== "sugarRing") throw new Error("no sugar ring");
      const n9 = perceived.ring.anomericSubstituent;
      expect(perceived.ring.form).toBe("furanose");
      expect(mol.atoms[n9]!.element).toBe("N");
      // N9 is the purine's three-connected ring nitrogen: C4, C8 and C1'.
      expect(isRingAtom(mol, n9)).toBe(true);
      expect(neighbours(mol, n9)).toHaveLength(3);
    }
  });

  it("takes a methyl glycoside's OR, not an OH, as the anomeric substituent", () => {
    for (const file of ["methyl-alpha-d-glucopyranoside.mol", "methyl-beta-d-glucopyranoside.mol"]) {
      const mol = fixture("sugar", file);
      const [perceived] = sugarRings(mol);
      if (perceived?.kind !== "sugarRing") throw new Error("no sugar ring");
      const o1 = perceived.ring.anomericSubstituent;
      const methyl = neighbours(mol, o1).find((id) => id !== perceived.ring.anomericCarbon)!;
      expect(mol.atoms[methyl]!.element).toBe("C");
      expect(neighbours(mol, methyl)).toEqual([o1]);
    }
  });

  it("leaves a ring with two heteroatoms undetermined until one is designated", () => {
    const mol = fixture("sugar", "lamivudine.mol");
    const [perceived] = sugarRings(mol);
    expect(perceived).toMatchObject({ kind: "undetermined", reason: "ring-heteroatoms" });
    if (perceived?.kind !== "undetermined") return;
    expect(perceived.atomIds.map((id) => mol.atoms[id]!.element).sort()).toEqual(["O", "S"]);
    const oxygen = perceived.atomIds.find((id) => mol.atoms[id]!.element === "O")!;

    const designated = perceiveSugarRing(mol, perceived.ringAtomIds, { ringHeteroatom: oxygen });
    if (designated.kind !== "sugarRing") throw new Error("designation did not resolve");
    // The anomeric carbon is the one carrying the cytosine N1.
    expect(mol.atoms[designated.ring.anomericSubstituent]!.element).toBe("N");
    // Its ring path runs through sulfur, so it is a sugar ring but not a
    // carbohydrate chain: nothing numbers it.
    expect(carbohydrateOfRing(mol, designated.ring)).toBeUndefined();
    expect(carbohydrates(mol)).toEqual([]);
  });

  it("reports a C-glycoside as a choice between its two candidate carbons", () => {
    const beta = fixture("projection", "beta-d-glucopyranose.mol");
    const [glucose] = sugarRings(beta);
    if (glucose?.kind !== "sugarRing") throw new Error("no sugar ring");
    // The anomeric OH's oxygen becomes a methyl carbon: 1-C-methyl, a C-glycoside.
    const cGlycoside = setElement(beta, glucose.ring.anomericSubstituent, "C");
    const [perceived] = sugarRings(cGlycoside);
    expect(perceived).toMatchObject({ kind: "needsChoice", choice: "anomericCarbon" });
    if (perceived?.kind !== "needsChoice") return;
    expect([...perceived.candidates].sort()).toEqual(
      [glucose.ring.anomericCarbon, glucose.ring.ringClosingCarbon].sort(),
    );
    expect(carbohydrates(cGlycoside)).toEqual([]);

    const designated = perceiveSugarRing(cGlycoside, perceived.ringAtomIds, {
      anomericCarbon: glucose.ring.anomericCarbon,
    });
    if (designated.kind !== "sugarRing") throw new Error("designation did not resolve");
    expect(designated.ring.anomericSubstituent).toBe(glucose.ring.anomericSubstituent);
    const unit = carbohydrateOfRing(cGlycoside, designated.ring)!;
    expect(carbohydrateLocant(unit, glucose.ring.anomericCarbon)).toBe("1");
    // The aglycone carbon is a substituent, not C0 of the chain.
    expect(unit.backbone).not.toContain(glucose.ring.anomericSubstituent);
  });

  it("reads glucono-1,5-lactone as a lactone, never as a pyranose", () => {
    // Oxidising beta-D-glucopyranose's anomeric OH to C=O gives the lactone:
    // C1 is then an ester carbon, sp2, and no anomeric centre at all.
    const beta = fixture("projection", "beta-d-glucopyranose.mol");
    const [glucose] = sugarRings(beta);
    if (glucose?.kind !== "sugarRing") throw new Error("no sugar ring");
    const c1 = glucose.ring.anomericCarbon;
    const o1 = glucose.ring.anomericSubstituent;
    const lactone = updateBond(beta, bondBetween(beta, c1, o1)!.id, { order: 2, stereo: "none" });
    expect(valenceIssues(lactone)).toEqual([]);

    expect(sugarRings(lactone)).toEqual([
      { kind: "undetermined", reason: "lactone", ringAtomIds: expect.any(Array), atomIds: [c1] },
    ]);
    expect(carbohydrates(lactone)).toEqual([]);
    // No designation turns an ester carbon into an anomeric one.
    const ring = glucose.ring.ringAtomIds;
    expect(perceiveSugarRing(lactone, ring, { anomericCarbon: c1, anomericSubstituent: o1 })).toMatchObject({
      kind: "undetermined",
      reason: "lactone",
    });
    // And it is not "a glycoside" to openRing: it is a lactone.
    expect(openRing(lactone, c1)).toMatchObject({ kind: "refused", reason: "lactone" });
  });

  it("does not report a plain lactone as a possible sugar ring", () => {
    // gamma-Butyrolactone: THF with a C=O beside the ring oxygen. Nothing
    // else is on the ring, so it is not even a candidate.
    const thf = dictionary("thf");
    const c2 = thf.atomIds.find(
      (id) => thf.atoms[id]!.element === "C" && neighbours(thf, id).some((o) => thf.atoms[o]!.element === "O"),
    )!;
    const added = addAtom(thf, { element: "O", pos: { x: thf.atoms[c2]!.pos.x, y: thf.atoms[c2]!.pos.y - 1 } });
    const gbl = addBond(added.molecule, { from: c2, to: added.id, order: 2 }).molecule;
    expect(valenceIssues(gbl)).toEqual([]);
    expect(sugarRings(gbl)).toEqual([]);
    expect(carbohydrates(gbl)).toEqual([]);
  });

  it("does not take solvents, carbocycles or aromatic rings for sugar rings", () => {
    for (const id of ["thf", "dioxane", "cyclohexane", "furan", "pyridine", "benzene", "caffeine"]) {
      const mol = dictionary(id);
      expect(sugarRings(mol), id).toEqual([]);
      expect(carbohydrates(mol), id).toEqual([]);
    }
    const furan = dictionary("furan");
    const ring = furan.atomIds.filter((atomId) => isRingAtom(furan, atomId));
    expect(perceiveSugarRing(furan, ring)).toMatchObject({ kind: "undetermined", reason: "unsaturated-ring" });
  });

  it("is memoised on topology, so a drag recomputes nothing", () => {
    const mol = fixture("projection", "alpha-d-glucopyranose.mol");
    sugarRings(mol);
    const before = sugarPerceptionComputationCount();
    let dragged = mol;
    for (let i = 0; i < 40; i++) {
      dragged = translateAtoms(dragged, [dragged.atomIds[0]!], { x: 0.01, y: 0 });
      carbohydrates(dragged);
    }
    expect(sugarPerceptionComputationCount()).toBe(before);
  });
});

// ---------------------------------------------------------------------------
// Numbering
// ---------------------------------------------------------------------------

describe("carbohydrate numbering", () => {
  it("numbers glucose from its aldehyde, whatever order its atoms were drawn in", () => {
    const drawn = glucoseOpen();
    // The same molecule with every atom re-minted in reverse order, so the
    // aldehyde carbon now has the HIGHEST id rather than one of the lowest.
    const reversed = buildMolecule((b) => {
      const map = new Map<AtomId, AtomId>();
      for (const id of [...drawn.atomIds].reverse()) {
        const atom = drawn.atoms[id]!;
        map.set(id, b.atom(atom.element, atom.pos));
      }
      for (const id of [...drawn.bondIds].reverse()) {
        const bond = drawn.bonds[id]!;
        b.bond(map.get(bond.from)!, map.get(bond.to)!, bond.order, bond.stereo);
      }
    });
    expect(reversed.atomIds.map((id) => reversed.atoms[id]!.element)).toEqual(
      [...drawn.atomIds].reverse().map((id) => drawn.atoms[id]!.element),
    );
    for (const mol of [drawn, reversed]) {
      const unit = only(mol);
      expect(unit).toMatchObject({ form: "open", parent: "aldose", firstLocant: 1, directionTied: false });
      expect(unit.backbone).toHaveLength(6);
      const c1 = atLocant(unit, "1");
      expect(bondsAt(mol, c1).some((bond) => bond.order === 2 && mol.atoms[otherEnd(bond, c1)]!.element === "O")).toBe(true);
      // C6 is the CH2OH: one carbon neighbour.
      const c6 = atLocant(unit, "6");
      expect(neighbours(mol, c6).filter((id) => mol.atoms[id]!.element === "C")).toHaveLength(1);
      expectResolved(mol, unit);
      expect(lettersByLocant(mol, unit)).toEqual({ 2: "R", 3: "S", 4: "R", 5: "R" });
    }
  });

  it("numbers fructose's ketone C2, with the CH2OH on it as C1", () => {
    const mol = fixture("projection", "d-fructose-open.mol");
    const unit = only(mol);
    expect(unit).toMatchObject({ parent: "ketose", firstLocant: 1 });
    const c2 = atLocant(unit, "2");
    expect(c2).toBe(unit.anchor);
    const c1 = atLocant(unit, "1");
    expect(neighbours(mol, c1).sort()).toEqual([c2, oxygenOn(mol, c1)].sort());
    expect(unit.backbone).toHaveLength(6);
  });

  it("numbers 2-deoxyribose by its chain from the aldehyde, the CH2 as C2", () => {
    const mol = fixture("projection", "2-deoxy-d-ribose-open.mol");
    const unit = only(mol);
    const c2 = atLocant(unit, "2");
    expect(neighbours(mol, c2).every((id) => mol.atoms[id]!.element === "C")).toBe(true);
    expect(atLocant(unit, "1")).toBe(unit.anchor);
    expect(unit.backbone).toHaveLength(5);
  });

  it("numbers only dihydroxyacetone's C2: its two ends tie", () => {
    const mol = fixture("sugar", "dihydroxyacetone.mol");
    const unit = only(mol);
    expect(unit).toMatchObject({ parent: "ketose", directionTied: true, firstLocant: 2 });
    expect(unit.backbone).toEqual([unit.anchor]);
  });

  it("numbers ring forms from the anomeric carbon, through the ring and on out of it", () => {
    const pyranose = fixture("projection", "beta-d-glucopyranose.mol");
    const p = only(pyranose);
    expect(p).toMatchObject({ form: "pyranose", parent: "aldose", firstLocant: 1 });
    expect(p.backbone).toHaveLength(6);
    expect(atLocant(p, "1")).toBe(p.ring!.anomericCarbon);
    expect(atLocant(p, "5")).toBe(p.ring!.ringClosingCarbon);

    const furanose = fixture("sugar", "alpha-d-glucofuranose.mol");
    const f = only(furanose);
    expect(f.form).toBe("furanose");
    expect(atLocant(f, "4")).toBe(f.ring!.ringClosingCarbon);
    expect(f.ring!.ringAtomIds).not.toContain(atLocant(f, "5"));

    const fructose = dictionary("beta-d-fructofuranose");
    const k = only(fructose);
    expect(k).toMatchObject({ form: "furanose", parent: "ketose" });
    expect(atLocant(k, "2")).toBe(k.ring!.anomericCarbon);
    expect(k.ring!.ringAtomIds).not.toContain(atLocant(k, "1"));
    expect(atLocant(k, "5")).toBe(k.ring!.ringClosingCarbon);
  });

  it("primes a nucleoside's sugar and leaves the base unnumbered", () => {
    const mol = fixture("projection", "adenosine.mol");
    const unit = only(mol);
    expect(unit.primed).toBe(true);
    expect(unit.backbone.map((id) => carbohydrateLocant(unit, id))).toEqual(["1′", "2′", "3′", "4′", "5′"]);
    const deoxy = only(fixture("sugar", "2-deoxyadenosine.mol"));
    expect(deoxy.primed).toBe(true);
    expect(deoxy.backbone).toHaveLength(5);
  });

  it("numbers both residues of sucrose, unprimed", () => {
    const mol = dictionary("sucrose");
    const units = carbohydrates(mol);
    expect(units.map((u) => [u.form, u.parent, u.primed])).toEqual(
      expect.arrayContaining([
        ["pyranose", "aldose", false],
        ["furanose", "ketose", false],
      ]),
    );
    expect(units).toHaveLength(2);
  });

  it("does not number a hemiacetal ring that is not a carbohydrate", () => {
    // Oxan-2-ol: a sugar RING (a real hemiacetal, with an anomeric carbon),
    // but its chain carries only the ring oxygen, so 1 to 5 would be a
    // carbohydrate numbering of something that is not a carbohydrate.
    const mol = buildMolecule((b) => {
      const ring = [b.atom("O"), b.atom("C"), b.atom("C"), b.atom("C"), b.atom("C"), b.atom("C")];
      for (let i = 0; i < 6; i++) b.bond(ring[i]!, ring[(i + 1) % 6]!);
      b.bond(ring[1]!, b.atom("O"));
    });
    expect(sugarRings(mol).map((r) => r.kind)).toEqual(["sugarRing"]);
    expect(carbohydrates(mol)).toEqual([]);
  });
});

// ---------------------------------------------------------------------------
// D/L and the two reference atoms
// ---------------------------------------------------------------------------

describe("D/L", () => {
  const CASES: readonly (readonly [string, () => Molecule, "D" | "L"])[] = [
    ["(R)-glyceraldehyde", () => fixture("projection", "r-glyceraldehyde.mol"), "D"],
    ["(S)-glyceraldehyde", () => fixture("projection", "s-glyceraldehyde.mol"), "L"],
    ["D-glucose", glucoseOpen, "D"],
    ["L-glucose", () => fixture("projection", "l-glucose-open.mol"), "L"],
    ["D-galactose", () => fixture("projection", "d-galactose-open.mol"), "D"],
    ["D-fructose", () => fixture("projection", "d-fructose-open.mol"), "D"],
    ["D-ribose", () => fixture("projection", "d-ribose-open.mol"), "D"],
    ["2-deoxy-D-ribose", () => fixture("projection", "2-deoxy-d-ribose-open.mol"), "D"],
    ["alpha-D-glucopyranose", () => fixture("projection", "alpha-d-glucopyranose.mol"), "D"],
    ["alpha-D-mannopyranose", () => fixture("projection", "alpha-d-mannopyranose.mol"), "D"],
    ["alpha-L-fucopyranose", () => fixture("projection", "alpha-l-fucopyranose.mol"), "L"],
    ["alpha-D-glucofuranose", () => fixture("sugar", "alpha-d-glucofuranose.mol"), "D"],
    ["beta-D-galactofuranose", () => fixture("sugar", "beta-d-galactofuranose.mol"), "D"],
    ["beta-D-fructofuranose", () => dictionary("beta-d-fructofuranose"), "D"],
    ["adenosine", () => fixture("projection", "adenosine.mol"), "D"],
    ["2'-deoxyadenosine", () => fixture("sugar", "2-deoxyadenosine.mol"), "D"],
    ["N-acetylneuraminic acid", () => fixture("sugar", "n-acetyl-beta-neuraminic-acid.mol"), "D"],
    // L-glycero-D-manno: the configurational atom is C6, in the L-glycero group.
    ["L-glycero-alpha-D-manno-heptopyranose", () => fixture("sugar", "l-glycero-alpha-d-manno-heptopyranose.mol"), "L"],
  ];

  for (const [name, load, expected] of CASES) {
    it(`reads ${name} as ${expected}, and its enantiomer as the other`, () => {
      const mol = load();
      const unit = only(mol);
      expectResolved(mol, unit);
      const reading = carbohydrateSeries(mol, unit);
      expect(reading).toEqual({ kind: expected, atomId: configurationalAtom(mol, unit) });
      const mirror = enantiomer(mol);
      expect(carbohydrateSeries(mirror, only(mirror)).kind).toBe(expected === "D" ? "L" : "D");
    });
  }

  it("does not depend on how the drawing is turned on the page", () => {
    const mol = glucoseOpen();
    for (const degrees of [90, 180, 270, 33]) {
      const turned = rotateAtoms(mol, mol.atomIds, { x: 0, y: 0 }, (degrees * Math.PI) / 180);
      expect(carbohydrateSeries(turned, only(turned)).kind, `${degrees}°`).toBe("D");
    }
  });

  it("calls dihydroxyacetone not applicable, never D by default", () => {
    const mol = fixture("sugar", "dihydroxyacetone.mol");
    expect(carbohydrateSeries(mol, only(mol))).toEqual({ kind: "notApplicable", reason: "no-stereocentre" });
  });

  it("is undetermined, not D, for a chain drawn without wedges", () => {
    let mol = glucoseOpen();
    for (const id of mol.bondIds) mol = setBondStereo(mol, id, "none");
    expect(carbohydrateSeries(mol, only(mol))).toMatchObject({ kind: "undetermined" });
  });

  it("uses C5 for BOTH reference atoms of alpha-D-glucofuranose (decision 141)", () => {
    const mol = fixture("sugar", "alpha-d-glucofuranose.mol");
    const unit = only(mol);
    const c5 = atLocant(unit, "5");
    // C5 is outside the ring and is still the anomeric reference atom:
    // "for simple aldoses up to aldohexoses ... the anomeric reference atom
    // and the configurational atom are the same" (2-Carb-6.2).
    expect(unit.ring!.ringAtomIds).not.toContain(c5);
    expect(configurationalAtom(mol, unit)).toBe(c5);
    expect(anomericReferenceAtom(mol, unit)).toBe(c5);
  });

  it("returns different atoms from the two functions where the name needs two prefixes", () => {
    // L-glycero-alpha-D-manno-heptopyranose: D-manno covers C2..C5 and
    // L-glycero C6. D/L of the whole name is read at C6; alpha is referred
    // to C5, the highest atom of the group next to the anomeric centre.
    const heptose = fixture("sugar", "l-glycero-alpha-d-manno-heptopyranose.mol");
    const h = only(heptose);
    expect(configurationalAtom(heptose, h)).toBe(atLocant(h, "6"));
    expect(anomericReferenceAtom(heptose, h)).toBe(atLocant(h, "5"));
    expect(configurationalAtom(heptose, h)).not.toBe(anomericReferenceAtom(heptose, h));

    // Neu5Ac, D-glycero-D-galacto: C8 against C7.
    const sialic = fixture("sugar", "n-acetyl-beta-neuraminic-acid.mol");
    const s = only(sialic);
    expect(s).toMatchObject({ parent: "ketose", form: "pyranose" });
    expect(configurationalAtom(sialic, s)).toBe(atLocant(s, "8"));
    expect(anomericReferenceAtom(sialic, s)).toBe(atLocant(s, "7"));
  });
});

// ---------------------------------------------------------------------------
// Alpha/beta
// ---------------------------------------------------------------------------

describe("alpha/beta", () => {
  const CASES: readonly (readonly [string, () => Molecule, "alpha" | "beta"])[] = [
    ["alpha-D-glucopyranose", () => fixture("projection", "alpha-d-glucopyranose.mol"), "alpha"],
    ["beta-D-glucopyranose", () => fixture("projection", "beta-d-glucopyranose.mol"), "beta"],
    ["alpha-D-mannopyranose", () => fixture("projection", "alpha-d-mannopyranose.mol"), "alpha"],
    ["beta-D-mannopyranose", () => dictionary("beta-d-mannopyranose"), "beta"],
    ["beta-D-galactopyranose", () => dictionary("beta-d-galactopyranose"), "beta"],
    ["alpha-L-fucopyranose", () => fixture("projection", "alpha-l-fucopyranose.mol"), "alpha"],
    ["alpha-D-glucofuranose", () => fixture("sugar", "alpha-d-glucofuranose.mol"), "alpha"],
    // The two that a "highest ring stereocentre" reference (C4) inverts: in
    // galactose C4 and C5 sit on opposite sides of the Fischer projection.
    ["beta-D-galactofuranose", () => fixture("sugar", "beta-d-galactofuranose.mol"), "beta"],
    ["alpha-D-galactofuranose", () => fixture("sugar", "alpha-d-galactofuranose.mol"), "alpha"],
    ["beta-D-fructofuranose", () => dictionary("beta-d-fructofuranose"), "beta"],
    ["beta-D-ribofuranose", () => dictionary("beta-d-ribofuranose"), "beta"],
    ["2-deoxy-beta-D-ribofuranose", () => dictionary("2-deoxy-beta-d-ribofuranose"), "beta"],
    ["adenosine", () => fixture("projection", "adenosine.mol"), "beta"],
    ["2'-deoxyadenosine", () => fixture("sugar", "2-deoxyadenosine.mol"), "beta"],
    ["methyl alpha-D-glucopyranoside", () => fixture("sugar", "methyl-alpha-d-glucopyranoside.mol"), "alpha"],
    ["methyl beta-D-glucopyranoside", () => fixture("sugar", "methyl-beta-d-glucopyranoside.mol"), "beta"],
    ["L-glycero-alpha-D-manno-heptopyranose", () => fixture("sugar", "l-glycero-alpha-d-manno-heptopyranose.mol"), "alpha"],
    ["N-acetyl-beta-neuraminic acid", () => fixture("sugar", "n-acetyl-beta-neuraminic-acid.mol"), "beta"],
  ];

  for (const [name, load, expected] of CASES) {
    it(`reads ${name} as ${expected}, and the other anomer as the other`, () => {
      const mol = load();
      const unit = only(mol);
      expectResolved(mol, unit);
      const reading = anomericConfiguration(mol, unit);
      expect(reading).toMatchObject({
        kind: expected,
        anomericCarbon: unit.ring!.anomericCarbon,
        referenceAtom: anomericReferenceAtom(mol, unit),
        substituent: unit.ring!.anomericSubstituent,
      });
      // Inverting the anomeric centre alone is the other anomer.
      const other = invertStereocentre(mol, unit.ring!.anomericCarbon);
      expect(anomericConfiguration(other, only(other)).kind).toBe(expected === "alpha" ? "beta" : "alpha");
      // Inverting everything keeps the anomer: alpha-D mirrors to alpha-L.
      const mirror = enantiomer(mol);
      expect(anomericConfiguration(mirror, only(mirror)).kind).toBe(expected);
    });
  }

  it("names adenosine's anomeric substituent N9 and methyl glucoside's the OMe oxygen", () => {
    const adenosine = fixture("projection", "adenosine.mol");
    const a = anomericConfiguration(adenosine, only(adenosine));
    if (a.kind !== "beta") throw new Error("adenosine is beta");
    expect(adenosine.atoms[a.substituent]!.element).toBe("N");
    const glycoside = fixture("sugar", "methyl-alpha-d-glucopyranoside.mol");
    const g = anomericConfiguration(glycoside, only(glycoside));
    if (g.kind !== "alpha") throw new Error("methyl alpha-D-glucopyranoside is alpha");
    expect(neighbours(glycoside, g.substituent).map((id) => glycoside.atoms[id]!.element).sort()).toEqual(["C", "C"]);
  });

  it("reads both residues of sucrose: alpha-glucopyranosyl, beta-fructofuranoside", () => {
    const mol = dictionary("sucrose");
    const readings = carbohydrates(mol).map((u) => [u.form, anomericConfiguration(mol, u).kind]);
    expect(readings).toEqual(
      expect.arrayContaining([
        ["pyranose", "alpha"],
        ["furanose", "beta"],
      ]),
    );
  });

  it("reads a wavy bond at the anomeric carbon as a mixture of anomers", () => {
    const mol = fixture("projection", "alpha-d-glucopyranose.mol");
    const unit = only(mol);
    const a = unit.ring!.anomericCarbon;
    let wavy = mol;
    for (const bond of bondsAt(mol, a)) {
      if (bond.stereo !== "none") wavy = setBondStereo(wavy, bond.id, "none");
    }
    const o1 = unit.ring!.anomericSubstituent;
    wavy = updateBond(wavy, bondBetween(wavy, a, o1)!.id, { from: a, to: o1, stereo: "wavy" });
    expect(anomericConfiguration(wavy, only(wavy))).toEqual({ kind: "mixture", anomericCarbon: a });
  });

  it("is not applicable to an open chain", () => {
    const mol = glucoseOpen();
    expect(anomericConfiguration(mol, only(mol))).toEqual({ kind: "notApplicable", reason: "open-chain" });
  });

  it("never says which way an alpha substituent points", () => {
    // Alpha is a relative configuration. The shortcut that ties it to a
    // direction on the page holds for a D-pyranose drawn one way and is false
    // for alpha-L-fucopyranose, so no chem-core source may carry it.
    const dir = dirname(fileURLToPath(import.meta.url));
    for (const file of readdirSync(dir).filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts"))) {
      const source = readFileSync(join(dir, file), "utf8");
      expect(source, file).not.toMatch(/alpha means/i);
      expect(source, file).not.toMatch(/anomeric (OH|oxygen|hydroxyl|substituent)\s+points/i);
    }
  });
});

// ---------------------------------------------------------------------------
// Cyclise and open
// ---------------------------------------------------------------------------

function cyclised(mol: Molecule, hydroxylLocant: string, anomer: Anomer): Extract<ReturnType<typeof cycliseSugar>, { kind: "cyclised" }> {
  const unit = only(mol);
  const result = cycliseSugar(mol, {
    carbonylCarbon: unit.anchor,
    hydroxylOxygen: oxygenOn(mol, atLocant(unit, hydroxylLocant)),
    anomer,
  });
  if (result.kind !== "cyclised") throw new Error(`refused: ${result.reason}`);
  expect(result.unmarked).toEqual([]);
  return result;
}

describe("cycliseSugar", () => {
  it("requires the anomer rather than defaulting to one", () => {
    const mol = glucoseOpen();
    const unit = only(mol);
    const options = { carbonylCarbon: unit.anchor, hydroxylOxygen: oxygenOn(mol, atLocant(unit, "5")) };
    expect(() => cycliseSugar(mol, options as never)).toThrow(/anomer/);
  });

  // Letters by locant are PubChem's names for each product. They are what the
  // product IS, never "the same as before": C3 of glucose is S in the chain
  // and the pyranose and R in the furanose, because its ligands' priorities
  // change when C4's OH becomes the ring oxygen.
  const PRODUCTS: readonly (readonly [string, () => Molecule, string, Anomer, string, Record<string, string>])[] = [
    ["D-glucose", glucoseOpen, "5", "alpha", "pyranose", { 1: "S", 2: "R", 3: "S", 4: "S", 5: "R" }],
    ["D-glucose", glucoseOpen, "5", "beta", "pyranose", { 1: "R", 2: "R", 3: "S", 4: "S", 5: "R" }],
    ["D-glucose", glucoseOpen, "4", "alpha", "furanose", { 1: "S", 2: "R", 3: "R", 4: "R", 5: "R" }],
    ["D-galactose", () => fixture("projection", "d-galactose-open.mol"), "5", "alpha", "pyranose", { 1: "S", 2: "R", 3: "S", 4: "R", 5: "R" }],
    ["D-galactose", () => fixture("projection", "d-galactose-open.mol"), "4", "beta", "furanose", { 1: "R", 2: "R", 3: "R", 4: "S", 5: "R" }],
    ["D-fructose", () => fixture("projection", "d-fructose-open.mol"), "5", "beta", "furanose", { 2: "R", 3: "S", 4: "S", 5: "R" }],
    ["D-fructose", () => fixture("projection", "d-fructose-open.mol"), "6", "beta", "pyranose", { 2: "R", 3: "S", 4: "R", 5: "R" }],
  ];

  for (const [name, load, locant, anomer, form, letters] of PRODUCTS) {
    it(`closes ${name} onto its C${locant} hydroxyl as the ${anomer}-${form}`, () => {
      const chain = load();
      expectResolved(chain, only(chain));
      const result = cyclised(chain, locant, anomer);
      const unit = only(result.molecule);
      expect(unit.form).toBe(form);
      expect(result.ring.form).toBe(form);
      expect(lettersByLocant(result.molecule, unit)).toEqual(letters);
      expect(anomericConfiguration(result.molecule, unit).kind).toBe(anomer);
      expect(carbohydrateSeries(result.molecule, unit).kind).toBe("D");
      expect(valenceIssues(result.molecule)).toEqual([]);
    });
  }

  it("turns the carbonyl oxygen into the anomeric OH and the hydroxyl into the ring oxygen", () => {
    const chain = glucoseOpen();
    const unit = only(chain);
    const carbonylO = neighbours(chain, unit.anchor).find((id) => chain.atoms[id]!.element === "O")!;
    const o5 = oxygenOn(chain, atLocant(unit, "5"));
    const { ring } = cyclised(chain, "5", "beta");
    expect(ring.anomericSubstituent).toBe(carbonylO);
    expect(ring.ringHeteroatom).toBe(o5);
    expect(ring.anomericCarbon).toBe(unit.anchor);
  });

  it("keeps every centre's parity against its own ligand order, both ways", () => {
    const chain = glucoseOpen();
    const expected = paritiesAgainst(chain, chain);
    for (const anomer of ["alpha", "beta", "mixture"] as const) {
      for (const locant of ["4", "5"]) {
        const result = cyclised(chain, locant, anomer);
        expect(paritiesAgainst(chain, result.molecule), `${anomer} C${locant}`).toEqual(expected);
        const opened = openRing(result.molecule, result.ring.anomericCarbon);
        if (opened.kind !== "opened") throw new Error(opened.reason);
        expect(constitution(opened.molecule)).toEqual(constitution(chain));
        expect(paritiesAgainst(chain, opened.molecule)).toEqual(expected);
        expect(lettersByLocant(opened.molecule, only(opened.molecule))).toEqual({ 2: "R", 3: "S", 4: "R", 5: "R" });
      }
    }
  });

  it("draws a mixture as a wavy bond at the new anomeric carbon", () => {
    const result = cyclised(glucoseOpen(), "5", "mixture");
    const a = result.ring.anomericCarbon;
    const bond = bondBetween(result.molecule, a, result.ring.anomericSubstituent)!;
    expect(bond).toMatchObject({ from: a, stereo: "wavy" });
    expect(anomericConfiguration(result.molecule, only(result.molecule))).toEqual({ kind: "mixture", anomericCarbon: a });
  });

  /** Every unbonded pair's distance, and every pair of crossing bonds sharing no atom. */
  function crowding(mol: Molecule): { closest: number; pair: string; crossings: string[] } {
    const pos = (id: AtomId) => mol.atoms[id]!.pos;
    let closest = Infinity;
    let pair = "";
    for (let i = 0; i < mol.atomIds.length; i++) {
      for (let j = i + 1; j < mol.atomIds.length; j++) {
        const [p, q] = [mol.atomIds[i]!, mol.atomIds[j]!];
        if (bondBetween(mol, p, q) !== undefined) continue;
        const d = Math.hypot(pos(p).x - pos(q).x, pos(p).y - pos(q).y);
        if (d < closest) [closest, pair] = [d, `${p} ${q}`];
      }
    }
    const side = (a: { x: number; y: number }, b: { x: number; y: number }, c: { x: number; y: number }) =>
      Math.sign((b.x - a.x) * (c.y - a.y) - (b.y - a.y) * (c.x - a.x));
    const crossings: string[] = [];
    for (let i = 0; i < mol.bondIds.length; i++) {
      for (let j = i + 1; j < mol.bondIds.length; j++) {
        const b = mol.bonds[mol.bondIds[i]!]!;
        const c = mol.bonds[mol.bondIds[j]!]!;
        if ([b.from, b.to].some((id) => id === c.from || id === c.to)) continue;
        const straddles = (s: typeof b, t: typeof b) =>
          side(pos(s.from), pos(s.to), pos(t.from)) * side(pos(s.from), pos(s.to), pos(t.to)) < 0;
        if (straddles(b, c) && straddles(c, b)) crossings.push(`${b.id} ${c.id}`);
      }
    }
    return { closest, pair, crossings };
  }

  /** The chain `ring` opens to (openRing keeps its coordinates), closed again as `anomer`. */
  function reclosed(ring: Molecule, anomer: Anomer): Extract<ReturnType<typeof cycliseSugar>, { kind: "cyclised" }> {
    const opened = openRing(ring, only(ring).ring!.anomericCarbon);
    if (opened.kind !== "opened") throw new Error(opened.reason);
    const again = cycliseSugar(opened.molecule, {
      carbonylCarbon: opened.carbonylCarbon,
      hydroxylOxygen: opened.hydroxylOxygen,
      anomer,
    });
    if (again.kind !== "cyclised") throw new Error(again.reason);
    expect(again.unmarked).toEqual([]);
    return again;
  }

  // What each layout is checked on: glucose's two ring sizes, a ketose's two
  // (two groups on C2), and the two sugars with long tails on neighbouring
  // ring carbons. Neu5Ac is the one that broke: its C5 N-acetyl and C6
  // glycerol tail, turned rigidly outward, landed atom on atom.
  const LAYOUTS: readonly (readonly [string, () => Extract<ReturnType<typeof cycliseSugar>, { kind: "cyclised" }>])[] = [
    ["alpha-D-glucopyranose", () => cyclised(glucoseOpen(), "5", "alpha")],
    ["alpha-D-glucofuranose", () => cyclised(glucoseOpen(), "4", "alpha")],
    ["beta-D-fructofuranose", () => cyclised(fixture("projection", "d-fructose-open.mol"), "5", "beta")],
    ["beta-D-fructopyranose", () => cyclised(fixture("projection", "d-fructose-open.mol"), "6", "beta")],
    ["alpha-Neu5Ac", () => reclosed(fixture("sugar", "n-acetyl-beta-neuraminic-acid.mol"), "alpha")],
    ["beta-Neu5Ac", () => reclosed(fixture("sugar", "n-acetyl-beta-neuraminic-acid.mol"), "beta")],
    ["L-glycero-beta-D-manno-heptopyranose", () => reclosed(fixture("sugar", "l-glycero-alpha-d-manno-heptopyranose.mol"), "beta")],
  ];

  for (const [name, build] of LAYOUTS) {
    it(`lays ${name}'s new ring out as a regular polygon with nothing on top of anything`, () => {
      const result = build();
      const mol = result.molecule;
      const ring = result.ring.ringAtomIds;
      const pos = (id: AtomId) => mol.atoms[id]!.pos;
      const lengths = mol.bondIds.map((id) => {
        const bond = mol.bonds[id]!;
        return Math.hypot(pos(bond.to).x - pos(bond.from).x, pos(bond.to).y - pos(bond.from).y);
      });
      const bond = lengths.sort((p, q) => p - q)[lengths.length >> 1]!;
      const ringLengths = ring.map((id, i) => {
        const next = ring[(i + 1) % ring.length]!;
        return Math.hypot(pos(next).x - pos(id).x, pos(next).y - pos(id).y);
      });
      for (const length of ringLengths) expect(length).toBeCloseTo(bond, 6);
      const cx = ring.reduce((s, id) => s + pos(id).x, 0) / ring.length;
      const cy = ring.reduce((s, id) => s + pos(id).y, 0) / ring.length;
      const radii = ring.map((id) => Math.hypot(pos(id).x - cx, pos(id).y - cy));
      for (const r of radii) expect(r).toBeCloseTo(radii[0]!, 6);
      // The ring oxygen is up and to the right of the anomeric carbon.
      expect(pos(result.ring.ringHeteroatom).y).toBeGreaterThan(pos(result.ring.anomericCarbon).y);
      // No unbonded pair within 0.9 of a bond (the layout aims for one), and
      // no two bonds crossing. The Neu5Ac pair was at 0.000, fructopyranose's
      // O1 and ring O at 0.60.
      const { closest, pair, crossings } = crowding(mol);
      expect(closest, pair).toBeGreaterThan(0.9 * bond);
      expect(crossings).toEqual([]);
      expect(result.collisions).toEqual({ atoms: [], bonds: [] });
    });
  }

  it("re-closes Neu5Ac to PubChem's letters, clear of itself", () => {
    // beta-Neu5Ac, CID 445063: (2S,4S,5R,6R) on the oxane, (1R,2R) on the
    // tail, i.e. C2 S, C4 S, C5 R, C6 R, C7 R, C8 R. Alpha differs at C2 only.
    const original = fixture("sugar", "n-acetyl-beta-neuraminic-acid.mol");
    expectResolved(original, only(original));
    const letters = { 2: "S", 4: "S", 5: "R", 6: "R", 7: "R", 8: "R" };
    expect(lettersByLocant(original, only(original))).toEqual(letters);
    const beta = reclosed(original, "beta").molecule;
    expect(lettersByLocant(beta, only(beta))).toEqual(letters);
    expect(anomericConfiguration(beta, only(beta)).kind).toBe("beta");
    const alpha = reclosed(original, "alpha").molecule;
    expect(lettersByLocant(alpha, only(alpha))).toEqual({ ...letters, 2: "R" });
    expect(anomericConfiguration(alpha, only(alpha)).kind).toBe("alpha");
    expect(carbohydrateSeries(alpha, only(alpha)).kind).toBe("D");
  });

  it("reports an overlap no rigid move can clear, and does not hide it", () => {
    // A hydroxyl hydrogen drawn exactly on top of C6: the C6 group is moved
    // rigidly, so the overlap comes along, and it is reported by atom id.
    const chain = glucoseOpen();
    const unit = only(chain);
    const c6 = atLocant(unit, "6");
    const o6 = oxygenOn(chain, c6);
    const h = addAtom(chain, { element: "H", pos: chain.atoms[c6]!.pos });
    const drawn = addBond(h.molecule, { from: o6, to: h.id }).molecule;
    const result = cycliseSugar(drawn, {
      carbonylCarbon: unit.anchor,
      hydroxylOxygen: oxygenOn(chain, atLocant(unit, "5")),
      anomer: "beta",
    });
    if (result.kind !== "cyclised") throw new Error(result.reason);
    expect(result.collisions.atoms).toEqual([[c6, h.id].sort()]);
    expect(result.collisions.bonds).toEqual([]);
  });

  it("drops hydrogen pins on the atoms whose valence changed, and a drawn hydroxyl H", () => {
    let chain = glucoseOpen();
    const unit = only(chain);
    const c1 = unit.anchor;
    const carbonylO = neighbours(chain, c1).find((id) => chain.atoms[id]!.element === "O")!;
    const c5 = atLocant(unit, "5");
    const o5 = oxygenOn(chain, c5);
    const o6 = oxygenOn(chain, atLocant(unit, "6"));
    // Pins that are right for the chain and wrong for the ring.
    chain = setExplicitHydrogenCount(chain, c1, 1);
    chain = setExplicitHydrogenCount(chain, carbonylO, 0);
    chain = setExplicitHydrogenCount(chain, o5, 1);
    chain = setExplicitHydrogenCount(chain, o6, 1);
    const result = cycliseSugar(chain, { carbonylCarbon: c1, hydroxylOxygen: o5, anomer: "beta" });
    if (result.kind !== "cyclised") throw new Error(result.reason);
    const mol = result.molecule;
    expect(mol.atoms[c1]!.explicitHydrogenCount).toBeUndefined();
    expect(mol.atoms[carbonylO]!.explicitHydrogenCount).toBeUndefined();
    expect(mol.atoms[o5]!.explicitHydrogenCount).toBeUndefined();
    // An atom whose bonds did not change keeps its pin.
    expect(mol.atoms[o6]!.explicitHydrogenCount).toBe(1);
    expect(valenceIssues(mol)).toEqual([]);

    // A hydroxyl hydrogen drawn as an atom goes with the bond it made room for.
    const plain = glucoseOpen();
    const h = addAtom(plain, { element: "H", pos: { x: plain.atoms[o5]!.pos.x + 0.7, y: plain.atoms[o5]!.pos.y - 0.7 } });
    const drawnH = addBond(h.molecule, { from: o5, to: h.id }).molecule;
    const withH = cycliseSugar(drawnH, { carbonylCarbon: c1, hydroxylOxygen: o5, anomer: "beta" });
    if (withH.kind !== "cyclised") throw new Error(withH.reason);
    expect(withH.molecule.atomIds).toHaveLength(drawnH.atomIds.length - 1);
    expect(valenceIssues(withH.molecule)).toEqual([]);
    expect(anomericConfiguration(withH.molecule, only(withH.molecule)).kind).toBe("beta");
  });

  it("refuses what it cannot do, with a reason", () => {
    const chain = glucoseOpen();
    const unit = only(chain);
    const c1 = unit.anchor;
    const carbonylO = neighbours(chain, c1).find((id) => chain.atoms[id]!.element === "O")!;
    const hydroxylAt = (locant: string) => oxygenOn(chain, atLocant(unit, locant));
    const refusal = (options: Parameters<typeof cycliseSugar>[1], m = chain) => {
      const result = cycliseSugar(m, options);
      return result.kind === "refused" ? result.reason : "cyclised";
    };
    expect(refusal({ carbonylCarbon: c1, hydroxylOxygen: hydroxylAt("3"), anomer: "alpha" })).toBe("ring-size");
    expect(refusal({ carbonylCarbon: c1, hydroxylOxygen: hydroxylAt("6"), anomer: "alpha" })).toBe("ring-size");
    expect(refusal({ carbonylCarbon: c1, hydroxylOxygen: carbonylO, anomer: "alpha" })).toBe("not-a-hydroxyl");
    expect(refusal({ carbonylCarbon: atLocant(unit, "2"), hydroxylOxygen: hydroxylAt("5"), anomer: "alpha" })).toBe("not-a-carbonyl");
    expect(refusal({ carbonylCarbon: "a999", hydroxylOxygen: hydroxylAt("5"), anomer: "alpha" })).toBe("no-such-atom");

    // No wedges: alpha has nothing to be alpha against. A mixture does not need it.
    let flat = chain;
    for (const id of flat.bondIds) flat = setBondStereo(flat, id, "none");
    expect(refusal({ carbonylCarbon: c1, hydroxylOxygen: hydroxylAt("5"), anomer: "alpha" }, flat)).toBe("reference-undetermined");
    expect(refusal({ carbonylCarbon: c1, hydroxylOxygen: hydroxylAt("5"), anomer: "mixture" }, flat)).toBe("cyclised");
  });

  it("builds the mutarotation figure in place: the chain and both anomers, three species", () => {
    // Decision 104: duplicate the chain twice, cyclise one copy alpha and the
    // other beta. One molecule, one undo timeline.
    const chain = glucoseOpen();
    const first = duplicateFragment(chain, chain.atomIds, { offset: { x: 8, y: 0 } });
    const second = duplicateFragment(first.molecule, chain.atomIds, { offset: { x: 16, y: 0 } });
    let figure = second.molecule;
    const unit = only(chain);
    const c1 = unit.anchor;
    const o5 = oxygenOn(chain, atLocant(unit, "5"));
    const alpha = cycliseSugar(figure, {
      carbonylCarbon: first.atomIdMap.get(c1)!,
      hydroxylOxygen: first.atomIdMap.get(o5)!,
      anomer: "alpha",
    });
    if (alpha.kind !== "cyclised") throw new Error(alpha.reason);
    const beta = cycliseSugar(alpha.molecule, {
      carbonylCarbon: second.atomIdMap.get(c1)!,
      hydroxylOxygen: second.atomIdMap.get(o5)!,
      anomer: "beta",
    });
    if (beta.kind !== "cyclised") throw new Error(beta.reason);
    figure = beta.molecule;

    expect(species(figure)).toHaveLength(3);
    const readings = carbohydrates(figure).map((u) => [u.form, anomericConfiguration(figure, u).kind]);
    expect(readings).toEqual([
      ["open", "notApplicable"],
      ["pyranose", "alpha"],
      ["pyranose", "beta"],
    ]);
    // The original chain did not move.
    for (const id of chain.atomIds) expect(figure.atoms[id]!.pos).toEqual(chain.atoms[id]!.pos);
  });
});

describe("stereo groups across the ring-chain edit", () => {
  /** `mol` with every stereocentre in one group of `kind`. */
  function grouped(mol: Molecule, kind: "and" | "or" | "abs"): Molecule {
    return withStereoGroups(mol, [{ kind, index: 1, atomIds: stereocenterAtoms(mol) }]);
  }

  it("keeps racemic glucose racemic: the new anomeric centre joins the chain's AND group", () => {
    const chain = grouped(glucoseOpen(), "and");
    expect(stereoGroupCoverage(chain)).toMatchObject({ kind: "whole", prefix: "rac-" });
    for (const anomer of ["alpha", "beta"] as const) {
      const result = cyclised(chain, "5", anomer);
      const c1 = result.ring.anomericCarbon;
      // Alpha is relative to C5, so C1 states what C5 states: rac, not an
      // absolute C1 on a racemic C2-C5.
      expect(stereoGroupsOf(result.molecule)).toEqual([
        { kind: "and", index: 1, atomIds: [...stereoGroupsOf(chain)[0]!.atomIds, c1].sort(compareIds) },
      ]);
      expect(stereoGroupCoverage(result.molecule)).toMatchObject({ kind: "whole", prefix: "rac-" });

      const opened = openRing(result.molecule, c1);
      if (opened.kind !== "opened") throw new Error(opened.reason);
      // Open again, C1 is a carbonyl carbon and in no group.
      expect(stereoGroupsOf(opened.molecule)).toEqual(stereoGroupsOf(chain));
      expect(stereoGroupCoverage(opened.molecule)).toMatchObject({ kind: "whole", prefix: "rac-" });
    }
  });

  it("puts the anomer in the reference atom's group whatever its kind, and a mixture in none", () => {
    const abs = cyclised(grouped(glucoseOpen(), "abs"), "5", "alpha");
    expect(stereoGroupAt(abs.molecule, abs.ring.anomericCarbon)).toMatchObject({ kind: "abs" });
    const rel = cyclised(grouped(glucoseOpen(), "or"), "4", "beta");
    expect(stereoGroupAt(rel.molecule, rel.ring.anomericCarbon)).toMatchObject({ kind: "or", index: 1 });
    // A wavy bond states no configuration, so it joins nothing.
    const mixture = cyclised(grouped(glucoseOpen(), "and"), "5", "mixture");
    expect(stereoGroupAt(mixture.molecule, mixture.ring.anomericCarbon)).toBeUndefined();
    // Ungrouped in, ungrouped out: no key appears.
    expect(Object.hasOwn(cyclised(glucoseOpen(), "5", "alpha").molecule, "stereoGroups")).toBe(false);
  });

  it("drops the old anomeric carbon from its group when the ring opens", () => {
    const ring = grouped(fixture("projection", "beta-d-glucopyranose.mol"), "and");
    const c1 = only(ring).ring!.anomericCarbon;
    expect(stereoGroupAt(ring, c1)).toBeDefined();
    const opened = openRing(ring, c1);
    if (opened.kind !== "opened") throw new Error(opened.reason);
    expect(stereoGroupAt(opened.molecule, c1)).toBeUndefined();
    expect(stereoGroupsOf(opened.molecule)[0]!.atomIds).toEqual(stereocenterAtoms(opened.molecule));
    expect(stereoGroupCoverage(opened.molecule)).toMatchObject({ kind: "whole", prefix: "rac-" });
  });
});

describe("openRing", () => {
  it("opens beta-D-glucopyranose to D-glucose", () => {
    const ring = fixture("projection", "beta-d-glucopyranose.mol");
    const unit = only(ring);
    const opened = openRing(ring, unit.ring!.anomericCarbon);
    if (opened.kind !== "opened") throw new Error(opened.reason);
    const chain = only(opened.molecule);
    expect(chain).toMatchObject({ form: "open", parent: "aldose", anchor: unit.ring!.anomericCarbon });
    expect(lettersByLocant(opened.molecule, chain)).toEqual({ 2: "R", 3: "S", 4: "R", 5: "R" });
    expect(carbohydrateSeries(opened.molecule, chain).kind).toBe("D");
    // Nothing is left marked on the carbon that is no longer a centre.
    expect(bondsAt(opened.molecule, chain.anchor).every((bond) => bond.from !== chain.anchor || bond.stereo === "none")).toBe(true);
    // And it closes again.
    const again = cycliseSugar(opened.molecule, {
      carbonylCarbon: opened.carbonylCarbon,
      hydroxylOxygen: opened.hydroxylOxygen,
      anomer: "beta",
    });
    if (again.kind !== "cyclised") throw new Error(again.reason);
    expect(anomericConfiguration(again.molecule, only(again.molecule)).kind).toBe("beta");
  });

  it("refuses a glycoside, which is an acetal and not a cyclised chain", () => {
    for (const mol of [fixture("sugar", "methyl-alpha-d-glucopyranoside.mol"), fixture("projection", "adenosine.mol")]) {
      const unit = only(mol);
      expect(openRing(mol, unit.ring!.anomericCarbon)).toMatchObject({ kind: "refused", reason: "glycoside" });
    }
    const chain = glucoseOpen();
    expect(openRing(chain, only(chain).anchor)).toMatchObject({ kind: "refused", reason: "not-a-sugar-ring" });
  });
});
