import { createRequire } from "node:module";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { beforeAll, describe, expect, it } from "vitest";
import {
  cipDescriptor,
  doubleBondDescriptor,
  readMolblock,
  stereocenterAtoms,
  stereogenicBonds,
  writeMolblock,
} from "@starter/chem-core";
import type { Molecule } from "@starter/chem-core";

import type { JSMolLike, RDKitModuleLike } from "./ops";

/**
 * chem-core's CIP letters against RDKit, live.
 *
 * chem-core never imports RDKit, so its own tests pin RDKit's letters as
 * literals. This file is what keeps those literals honest: it reads the SAME
 * checked-in molblocks (packages/chem-core/test/fixtures) into RDKit and asks
 * `get_stereo_tags`, and also hands RDKit chem-core's own molblock export of
 * each molecule, so a letter that drifts on either side fails here.
 *
 * Decision 43's named heteroatom centres are asserted by name: phosphorus
 * ylide P=C, sulfilimine S=N, selenoxide Se=O and arsine As(III).
 *
 * WHERE chem-core REFUSES DELIBERATELY (escalated, not a mismatch):
 *   phosphate-diester-anion   RDKit "(?)" too; =O and O− differ by charge only.
 *   branch-phosphoryl         RDKit's letter depends on drawing P=O or P+–O−.
 *
 * WHERE RDKit's MOLFILE PARSER, not its CIP labeller, is what refuses:
 * `RDKIT_MOLFILE_STEREO_BLIND` below. RDKit 2025.03.4 reads the selenoxide
 * molblock (which RDKit itself wrote, hash bond Se→CH3) back as the flat
 * `C[Se](=O)c1ccccc1` and tags the Se `(?)`; the SAME compound from its SMILES
 * tags `(R)`. So the wedge, not the ranking, is what is lost, and the oracle
 * for those fixtures is RDKit's reading of the checked-in SMILES. chem-core
 * reads the wedge and agrees with that reading.
 */

const require = createRequire(import.meta.url);

/** get_stereo_tags is on the real JSMol; the shared interface omits it. */
type TaggedMol = JSMolLike & { get_stereo_tags(): string };

let RDKit: RDKitModuleLike;

beforeAll(async () => {
  const initRDKitModule = require("@rdkit/rdkit") as () => Promise<RDKitModuleLike>;
  RDKit = await initRDKitModule();
}, 60_000);

const FIXTURES = join(import.meta.dirname, "..", "..", "..", "..", "chem-core", "test", "fixtures");

const REFUSED = new Set(["phosphate-diester-anion", "branch-phosphoryl"]);

/**
 * Fixtures whose configuration RDKit's molfile parser drops. Their molblocks
 * were generated by RDKit from the SMILES beside them, so atom order is the
 * same in both and the SMILES parse is the oracle. Keep this set as small as
 * the evidence: a name added here is a claim about RDKit's V2000 reader, and
 * `loses the wedge in the molblock` below re-proves it every run.
 */
const RDKIT_MOLFILE_STEREO_BLIND = new Set(["selenoxide"]);

interface Letters {
  readonly atoms: Record<string, string>;
  readonly bonds: Record<string, string>;
}

function rdkitLetters(molblock: string): Letters {
  const mol = RDKit.get_mol(molblock, JSON.stringify({ removeHs: false })) as TaggedMol | null;
  if (mol === null) throw new Error("RDKit refused the molblock");
  try {
    const tags = JSON.parse(mol.get_stereo_tags()) as {
      CIP_atoms: [number, string][];
      CIP_bonds: [number, number, string][];
    };
    const atoms: Record<string, string> = {};
    for (const [index, label] of tags.CIP_atoms) atoms[`a${index + 1}`] = label.replace(/[()]/g, "");
    const bonds: Record<string, string> = {};
    for (const [a, b, label] of tags.CIP_bonds) {
      bonds[[`a${a + 1}`, `a${b + 1}`].sort().join("=")] = label.replace(/[()]/g, "");
    }
    return { atoms, bonds };
  } finally {
    mol.delete();
  }
}

function chemCoreLetters(mol: Molecule): Letters {
  const atoms: Record<string, string> = {};
  for (const id of stereocenterAtoms(mol)) {
    const d = cipDescriptor(mol, id);
    atoms[id] = d === undefined ? "-" : d.kind === "undetermined" ? "?" : d.kind;
  }
  const bonds: Record<string, string> = {};
  for (const bondId of stereogenicBonds(mol)) {
    const bond = mol.bonds[bondId]!;
    const d = doubleBondDescriptor(mol, bondId);
    bonds[[bond.from, bond.to].sort().join("=")] = d === undefined ? "-" : d.kind === "undetermined" ? "?" : d.kind;
  }
  return { atoms, bonds };
}

interface Fixture {
  readonly name: string;
  readonly molblock: string;
  readonly smiles: string;
}

function cipCases(): Record<string, { molblock: string; smiles: string }> {
  return (
    JSON.parse(readFileSync(join(FIXTURES, "cip", "cases.json"), "utf8")) as {
      cases: Record<string, { molblock: string; smiles: string }>;
    }
  ).cases;
}

function allFixtures(): Fixture[] {
  const out: Fixture[] = [];
  const manifest = JSON.parse(readFileSync(join(FIXTURES, "projection", "manifest.json"), "utf8")) as {
    fixtures: { file: string; smiles: string }[];
  };
  for (const { file, smiles } of manifest.fixtures) {
    out.push({ name: file, molblock: readFileSync(join(FIXTURES, "projection", file), "utf8"), smiles });
  }
  for (const [name, { molblock, smiles }] of Object.entries(cipCases())) out.push({ name, molblock, smiles });
  return out;
}

describe("chem-core CIP letters against RDKit get_stereo_tags", () => {
  it("agrees on every lettered unit of every fixture", () => {
    for (const { name, molblock, smiles } of allFixtures()) {
      const blind = RDKIT_MOLFILE_STEREO_BLIND.has(name);
      const expected = rdkitLetters(blind ? smiles : molblock);
      const mol = readMolblock(molblock).molecule;
      const found = chemCoreLetters(mol);
      if (REFUSED.has(name)) {
        expect(Object.values(found.atoms), name).toContain("?");
        continue;
      }
      // Every letter RDKit gives, chem-core gives. chem-core may list extra
      // centres RDKit leaves unlabelled, but only as undetermined.
      for (const [atomId, letter] of Object.entries(expected.atoms)) {
        if (letter === "?") continue;
        expect(found.atoms[atomId], `${name} ${atomId}`).toBe(letter);
      }
      for (const [atomId, letter] of Object.entries(found.atoms)) {
        if (letter !== "?") expect(expected.atoms[atomId], `${name} ${atomId}`).toBe(letter);
      }
      expect(found.bonds, name).toEqual(expected.bonds);

      // And RDKit reads chem-core's own export of the drawing the same way —
      // except where RDKit's own molfile reading is what is blind, since then
      // no molblock anyone writes can carry the configuration into it.
      if (!blind) {
        const roundTrip = rdkitLetters(writeMolblock(mol));
        expect(roundTrip.atoms, `${name} via writeMolblock`).toEqual(expected.atoms);
      }
    }
  });

  it("matches RDKit on decision 43's named heteroatom centres", () => {
    const cases = cipCases();
    for (const [name, atomId, letter] of [
      ["phosphorus-ylide", "a2", "R"],
      ["sulfilimine", "a2", "S"],
      ["selenoxide", "a2", "R"],
      ["arsine", "a2", "R"],
    ] as const) {
      const { molblock, smiles } = cases[name]!;
      const rdkitSource = RDKIT_MOLFILE_STEREO_BLIND.has(name) ? smiles : molblock;
      expect(rdkitLetters(rdkitSource).atoms[atomId], `RDKit ${name}`).toBe(letter);
      // chem-core always reads the DRAWING, blindness or not.
      const mol = readMolblock(molblock).molecule;
      expect(cipDescriptor(mol, atomId), `chem-core ${name}`).toEqual({ kind: letter });
    }
  });

  it("loses the wedge in the molblock exactly where the blind set says so", () => {
    // The exemption above is a claim about RDKit, so it is re-proved rather
    // than trusted: each blind fixture must LETTER from its SMILES and REFUSE
    // from its molblock. When a future RDKit fixes its V2000 reader this test
    // fails and the name comes back out of the set.
    const cases = cipCases();
    for (const name of RDKIT_MOLFILE_STEREO_BLIND) {
      const { molblock, smiles } = cases[name]!;
      const fromSmiles = Object.values(rdkitLetters(smiles).atoms);
      expect(fromSmiles, `${name} from SMILES`).not.toContain("?");
      expect(fromSmiles.length, `${name} from SMILES`).toBeGreaterThan(0);
      expect(Object.values(rdkitLetters(molblock).atoms), `${name} from molblock`).toContain("?");
    }
  });
});
